### ISSUE TITLE
OutOfMemoryError when collecting children terms

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1086]
The stack trace does not indicate the input that caused this problem. It might be possible to figure this out with the Apache access logs.

The frontend logic should have some limit to the number of terms that can be passed on to the ontology service to prevent inference abuses.

```
[Gemma - http-nio-8181-exec-93 (2024-04-05 18:53:55,320)] ERROR org.springframework.transaction.interceptor.TransactionAspectSupport.completeTransactionAfterThrowing(496) | Application exception overridden by rollback exception
OutOfMemoryError:
java.lang.OutOfMemoryError
    at java.util.ArrayList.hugeCapacity(ArrayList.java:272)
    at java.util.ArrayList.grow(ArrayList.java:265)
    at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241)
    at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233)
```

https://pavlidis-lab.slack.com/archives/C02LZHP6RB3/p1712368435579559

**Comment by arteymix** [comment]
It's also not possible to tell beforehand how many children terms will be retrieved. If one asks for `owl:Thing`, everything we have could be potentially returned.

**Comment by arteymix** [comment]
This will be alleviated significantly by f21e379e7d8017e0d27065a26f526173bf9c3750 by interrupting ontology queries taking more than 30 seconds.

**Comment by arteymix** [comment]
This should be completely resolved with the search index and inference improvements targeting the next release of baseCode.
