### ISSUE TITLE
Duplicate row name 170942 when adding RNA-Seq data

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1091]
```
java.lang.IllegalArgumentException: Duplicate row name 170942
	at ubic.basecode.dataStructure.matrix.AbstractMatrix.setRowName(AbstractMatrix.java:330) ~[baseCode-1.1.21.jar:?]
	at ubic.basecode.dataStructure.matrix.AbstractMatrix.setRowNames(AbstractMatrix.java:349) ~[baseCode-1.1.21.jar:?]
	at ubic.basecode.io.reader.DoubleMatrixReader.createMatrix(DoubleMatrixReader.java:262) ~[baseCode-1.1.21.jar:?]
	at ubic.basecode.io.reader.DoubleMatrixReader.read(DoubleMatrixReader.java:157) ~[baseCode-1.1.21.jar:?]
	at ubic.basecode.io.reader.DoubleMatrixReader.read(DoubleMatrixReader.java:217) ~[baseCode-1.1.21.jar:?]
	at ubic.basecode.io.reader.DoubleMatrixReader.read(DoubleMatrixReader.java:180) ~[baseCode-1.1.21.jar:?]
	at ubic.gemma.core.apps.RNASeqDataAddCli.doWork(RNASeqDataAddCli.java:208) ~[gemma-cli-1.31.3.jar:?]
	at ubic.gemma.core.util.AbstractCLI.executeCommand(AbstractCLI.java:210) [gemma-cli-1.31.3.jar:?]
	at ubic.gemma.core.apps.GemmaCLI.main(GemmaCLI.java:243) [gemma-cli-1.31.3.jar:?]

**Comment by arteymix** [comment]
Looks like this is an issue with Pandas 2.0.2 that produced duplicated keys in the concatenated matrix. I'll transfer this issue to the RNA-Seq pipeline tracker.
