### ISSUE TITLE
A name is insufficient to retrieve a unique quantitation type (for GSE28253)

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1152]
Looks like we might have multiple QTs with the same name for GSE28253.

This should not produce a 500-error.

```
[Gemma - http-nio-8181-exec-63 (2024-06-17 04:15:29,920)] ERROR ubic.gemma.rest.providers.AbstractExceptionMapper.toResponse(65) | Unhandled exception was raised for GET http://localhost:8181/rest/v2/datasets/GSE28253/data/raw?quantitationType=gemma.raw
UnsupportedOperationException: A name is insufficient to retrieve a unique quantitation type.
java.lang.UnsupportedOperationException: A name is insufficient to retrieve a unique quantitation type.
    at ubic.gemma.rest.util.args.QuantitationTypeByNameArg.getEntity(QuantitationTypeByNameArg.java:18)
    at ubic.gemma.rest.util.args.QuantitationTypeByNameArg.getEntity(QuantitationTypeByNameArg.java:9)
    at ubic.gemma.rest.util.args.AbstractEntityArgService.getEntity(AbstractEntityArgService.java:76)
    at ubic.gemma.rest.util.args.QuantitationTypeArgService.getEntity(QuantitationTypeArgService.java:19)
```

**Comment by ppavlidis** [comment]
I don't see anything out of order
https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=5247
<img width="496" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/b21effa6-9a24-4b88-8680-83304347762c">

**Comment by arteymix** [comment]
Indeed, it's not about the dataset at all. The QT arg by name is not implemented, so passing a non-numerical value to the endpoint will always trigger this error.

**Comment by arteymix** [comment]
Ok, it's fully implemented now ;)
