### ISSUE TITLE
IllegalArgumentException: Cannot pass vectors from more than one quantitation type: QuantitationType Id=532865 Name=VALUE - Processed version General Type=QUANTITATIVE Type=AMOUNT Scale=LOG2 Representation=DOUBLE [Normalized] [Preferred] vs QuantitationType Id=532864 Name=VALUE - Processed version General Type=QUANTITATIVE Type=AMOUNT Scale=LOG2 Representation=DOUBLE [Normalized] [Preferred]

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1177]
```
IllegalArgumentException: Cannot pass vectors from more than one quantitation type: QuantitationType Id=532865 Name=VALUE - Processed version General Type=QUANTITATIVE Type=AMOUNT Scale=LOG2 Representation=DOUBLE [Normalized] [Preferred] vs QuantitationType Id=532864 Name=VALUE - Processed version General Type=QUANTITATIVE Type=AMOUNT Scale=LOG2 Representation=DOUBLE [Normalized] [Preferred]
java.lang.IllegalArgumentException: Cannot pass vectors from more than one quantitation type: QuantitationType Id=532865 Name=VALUE - Processed version General Type=QUANTITATIVE Type=AMOUNT Scale=LOG2 Representation=DOUBLE [Normalized] [Preferred] vs QuantitationType Id=532864 Name=VALUE - Processed version General Type=QUANTITATIVE Type=AMOUNT Scale=LOG2 Representation=DOUBLE [Normalized] [Preferred]
    at ubic.gemma.core.datastructure.matrix.BaseExpressionDataMatrix.selectVectors(BaseExpressionDataMatrix.java:387)
    at ubic.gemma.core.datastructure.matrix.ExpressionDataDoubleMatrix.<init>(ExpressionDataDoubleMatrix.java:76)
    at ubic.gemma.core.analysis.service.ExpressionDataMatrixServiceImpl…
```

Example: https://gemma.msl.ubc.ca/rest/v2/datasets/GSE29361/data/processed

**Comment by arteymix** [comment]
Looks like GSE29361 has to sets of processed vectors...

**Comment by ppavlidis** [comment]
Still applies in Gemma 2.0-alpha: BaseExpressionDataMatrix.selectVectors() still raises on multiple-preferred-processed-QT datasets, and the affected REST endpoint /rest/v2/datasets/{}/data/processed remains in 2.0. Needs focused follow-up: decide whether to (a) auto-pick the highest-id preferred QT in ExpressionDataMatrixServiceImpl, or (b) backfill curation to ensure only one preferred processed QT per EE.

**Comment by ppavlidis** [comment]
Gemma 2 disposition: Won't fix
