### ISSUE TITLE
Error marshalling java.lang.Long: Format error converting XXXXX

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1199]
I had to replace the actual value with XXXXX since it contains a username.

```
org.directwebremoting.extend.MarshallException: Error marshalling java.lang.Long: Format error converting XXXXX. See the logs for more details.
        at org.directwebremoting.convert.PrimitiveConverter.convertInbound(PrimitiveConverter.java:53) ~[dwr-2.0.11-RELEASE.jar:?]
        at org.directwebremoting.dwrp.DefaultConverterManager.convertInbound(DefaultConverterManager.java:167) ~[dwr-2.0.11-RELEASE.jar:?]
        at org.directwebremoting.convert.BasicObjectConverter.convertInbound(BasicObjectConverter.java:139) ~[dwr-2.0.11-RELEASE.jar:?]
        at org.directwebremoting.dwrp.DefaultConverterManager.convertInbound(DefaultConverterManager.java:167) ~[dwr-2.0.11-RELEASE.jar:?]
        at org.directwebremoting.dwrp.BaseCallMarshaller.marshallInbound(BaseCallMarshaller.java:155) [dwr-2.0.11-RELEASE.jar:?]
        at org.directwebremoting.servlet.PlainCallHandler.handle(PlainCallHandler.java:44) [dwr-2.0.11-RELEASE.jar:?]
        at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:101) [dwr-2.0.11-RELEASE.jar:?]
        at org.directwebremoting.spring.DwrController.handleRequestInternal(DwrController.java:234) [dwr-2.0.11-RELEASE.jar:?]
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153) [spring-webmvc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48) [spring-webmvc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933) [spring-webmvc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867) [spring-webmvc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951) [spring-webmvc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:853) [spring-webmvc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) [servlet-api.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827) [spring-webmvc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) [servlet-api.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) [catalina.jar:9.0.80]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.80]
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:182) [sitemesh-2.5.0.jar:?]
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85) [sitemesh-2.5.0.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.80]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.80]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106) [spring-web-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.80]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.80]
        at ubic.gemma.web.metrics.binder.servlet.ServletMetricsFilter.doFilterInternal(ServletMetricsFilter.java:59) [classes/:?]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106) [spring-web-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.80]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.80]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat-websocket.jar:9.0.80]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [catalina.jar:9.0.80]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.80]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-3.2.10.RELEASE.jar:?]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) [spring-security-web-3.2.10.RELEASE.jar:?]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) [spring-security-web-3.2.10.RELEASE.jar:?]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.10.RELEASE.jar:?]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-3.2.10.RELEASE.jar:?]
```

**Comment by arteymix** [comment]
I witnessed this on a curator computer when viewing an experiment.

**Comment by ppavlidis** [comment]
Closing as won't fix for Gemma 2.0-alpha: this is a DWR (DirectWebRemoting) marshalling error. The DWR stack has been removed on the renovations branch (see gemma-web/pom.xml comment 'DWR removed on the renovations branch — the Spring-XML <dwr:remote> bindings are gone'). The code path that produced this error no longer exists in 2.0.

**Comment by ppavlidis** [comment]
Gemma 2 disposition: Obsolete/Irrelevant
