### ISSUE TITLE
NoSuchElementException when writing an analysis result set to disk

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1205]
```
NoSuchElementException:
java.util.NoSuchElementException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1471)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1493)
    at org.hibernate.collection.internal.AbstractPersistentCollection$IteratorProxy.next(AbstractPersistentCollection.java:810)
    at ubic.gemma.core.analysis.service.ExpressionDataFileServiceImpl.analysisResultSetWithContrastsToString(ExpressionDataFileServiceImpl.java:620)
    at ubic.gemma.core.analysis.service.ExpressionDataFileServiceImpl.convertDiffExpressionResultSetData(ExpressionDataFileServiceImpl.java:795)
    at ubic.gemma.core.analysis.service.ExpressionDataFileServiceImpl.writeDiffExArchiveFile(ExpressionDataFileServiceImpl.java:399)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy2493.writeDiffExArchiveFile(Unknown Source)
    at ubic.gemma.core.analysis.expression.diff.DifferentialExpressionAnalyzerServiceImpl.persistAnalysis(DifferentialExpressionAnalyzerServiceImpl.java:233)
    at ubic.gemma.core.analysis.expression.diff.DifferentialExpressionAnalyzerServiceImpl.persistAnalyses(DifferentialExpressionAnalyzerServiceImpl.java:461)
    at ubic.gemma.core.analysis.expression.diff.DifferentialExpressionAnalyzerServiceImpl.redoAnalysis(DifferentialExpressionAnalyzerServiceImpl.java:162)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy2495.redoAnalysis(Unknown Source)
    at ubic.gemma.core.tasks.analysis.diffex.DifferentialExpressionAnalysisTaskImpl.doAnalysis(DifferentialExpressionAnalysisTaskImpl.java:98)
    at ubic.gemma.core.tasks.analysis.diffex.DifferentialExpressionAnalysisTaskImpl.call(DifferentialExpressionAnalysisTaskImpl.java:77)
    at ubic.gemma.core.tasks.analysis.diffex.DifferentialExpressionAnalysisTaskImpl.call(DifferentialExpressionAnalysisTaskImpl.java:43)
    at ubic.gemma.core.job.ExecutingTask.call(ExecutingTask.java:51)
    at ubic.gemma.core.job.ExecutingTask.call(ExecutingTask.java:26)
    at org.springframework.security.concurrent.DelegatingSecurityContextCallable.call(DelegatingSecurityContextCallable.java:83)
    at ubic.gemma.core.job.TaskRunningServiceImpl.lambda$submitTask$0(TaskRunningServiceImpl.java:140)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)

**Comment by arteymix** [comment]
The line causing this fails if a result set does not have any associated factors:

```java
ExperimentalFactor ef = resultSet.getExperimentalFactors().iterator().next();
```

I'm not sure if this is possible, but I'll add a check in the serialization logic.

**Comment by arteymix** [comment]
I've added a check and did some cleanups. If it happens again, we'll be able to tell which RS is causing this.

Also, I couldn't find any instance of such a RS in the database.
