### ISSUE TITLE
Add arguments to listGEOData to match other experiment-oriented CLIs

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1209]
Curators have been asking to have the capabilities to process individual experiments.

This command is not designed to deal with experiments already in Gemma, so we cannot implement all the options.

**Comment by arteymix** [comment]
I'm assigning @SalvaSherif2532 for testing ;)

**Comment by SalvaSherif2532** [comment]
The -accession works as intended :)) When I tried passing a file using -accessionFile with one GSE per line, I got the following error: 

```
Options: -accessionFile /home/ssherif/text_files/missing_keys_scRNA.txt
2024-08-23 11:31:57,553 INFO 1760011 [main] u.g.c.u.AbstractAuthenticatedCLI.authenticate(111) | Logged in as ssherif
Gemma CLI error: java.lang.ClassCastException - class java.io.File cannot be cast to class java.nio.file.Path (java.io.File and java.nio.file.Path are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.io.File cannot be cast to class java.nio.file.Path (java.io.File and java.nio.file.Path are in module java.base of loader 'bootstrap')
    at ubic.gemma.core.apps.GeoGrabberCli.processOptions(GeoGrabberCli.java:160)
    at ubic.gemma.core.util.AbstractCLI.executeCommand(AbstractCLI.java:185)
    at ubic.gemma.core.apps.GemmaCLI.main(GemmaCLI.java:288)```
