### ISSUE TITLE
Error while visualizing DEA results for a data sets

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#1222]
For https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=33708

Clicking on the "view top genes" for some of the contrasts yields an error. (with some others it is okay)

<img width="427" alt="image" src="https://github.com/user-attachments/assets/800f4a17-8424-4c5a-bf5e-8ebab3d5baf4">

It is possible this is a duplicate of #356 but that issue has no context.

```
[Gemma - http-nio-8181-exec-128 (2024-09-11 15:12:14,306)] INFO ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionResultDaoImpl.findInResultSet(560) | Top hits already in cache
[Gemma - http-nio-8181-exec-128 (2024-09-11 15:12:14,361)] WARN ubic.gemma.core.visualization.ExperimentalDesignVisualizationServiceImpl.getExperimentForVector(522) | Vector is sliced, but the experiment is not a subset! null element=CompositeSequenceValueObject Id=21676195
[Gemma - http-nio-8181-exec-128 (2024-09-11 15:12:14,382)] WARN org.directwebremoting.util.CommonsLoggingOutput.warn(67) | Method execution failed:
java.lang.IllegalArgumentException: Primary factor not in the list of factors
        at ubic.gemma.core.datastructure.matrix.ExpressionDataMatrixColumnSort.orderFactorsByExperimentalDesign(ExpressionDataMatrixColumnSort.java:330) ~[gemma-core-1.31.10.jar:?]
        at ubic.gemma.core.datastructure.matrix.ExpressionDataMatrixColumnSort.orderByExperimentalDesign(ExpressionDataMatrixColumnSort.java:279) ~[gemma-core-1.31.10.jar:?]
        at ubic.gemma.core.datastructure.matrix.ExpressionDataMatrixColumnSort.orderByExperimentalDesign(ExpressionDataMatrixColumnSort.java:230) ~[gemma-core-1.31.10.jar:?]
        at ubic.gemma.core.visualization.ExperimentalDesignVisualizationServiceImpl.getExperimentalDesignLayout(ExperimentalDesignVisualizationServiceImpl.java:431) ~[gemma-core-1.31.10.jar:?]
        at ubic.gemma.core.visualization.ExperimentalDesignVisualizationServiceImpl.prepare(ExperimentalDesignVisualizationServiceImpl.java:615) ~[gemma-core-1.31.10.jar:?]
        at ubic.gemma.core.visualization.ExperimentalDesignVisualizationServiceImpl.sortVectorDataByDesign(ExperimentalDesignVisualizationServiceImpl.java:143) ~[gemma-core-1.31.10.jar:?]
        at ubic.gemma.web.controller.expression.experiment.DEDVController.getDEDVForDiffExVisualizationByThreshold(DEDVController.java:438) ~[classes/:?]
        at sun.reflect.GeneratedMethodAccessor3031.invoke(Unknown Source) ~[?:?]

```

**Comment by ppavlidis** [comment]
Can no longer reproduce this
