### ISSUE TITLE
Error when using splitExperiment CLI for GSE123919

### ISSUE THREAD

**Issue by SalvaSherif2532** [PavlidisLab/Gemma#1267]
Stack trace:

```
========= Gemma CLI invocation of splitExperiment ============
Options: -e GSE123919 -factor collection_of_material
2024-10-24 11:26:21,315 INFO 1013781 [main] u.g.c.u.AbstractAuthenticatedCLI.authenticate(111) | Logged in as ssherif
2024-10-24 11:26:21,456 INFO 1013781 [main] u.g.c.a.ExpressionExperimentManipulatingCLI.processOptions(244) | Final dataset: ExpressionExperiment Id=15144 Name=Translational profiling of dorsal root ganglia and spinal cord in a mouse model of neuropathic pain Short Name=GSE123919
2024-10-24 11:26:21,642 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(125) | Fetching raw expression data vectors ... 
2024-10-24 11:26:23,468 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(140) | 35205 vectors for QuantitationType Id=543625 Name=log2cpm General Type=QUANTITATIVE Type=AMOUNT Scale=LOG2 Representation=DOUBLE [Recomputed From Raw] [Preferred]; preferred=true
2024-10-24 11:26:24,472 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(140) | 35205 vectors for QuantitationType Id=543627 Name=Counts General Type=QUANTITATIVE Type=COUNT Scale=COUNT Representation=DOUBLE [Recomputed From Raw] [Preferred]; preferred=false
2024-10-24 11:26:25,347 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(140) | 35205 vectors for QuantitationType Id=543629 Name=RPKM General Type=QUANTITATIVE Type=AMOUNT Scale=LINEAR Representation=DOUBLE [Normalized] [Recomputed From Raw] [Preferred]; preferred=false
2024-10-24 11:26:25,507 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(243) | 1 unused factor values removed for ExperimentalFactor Name=organism part Type=CATEGORICAL Category=Characteristic Category=organism part [http://www.ebi.ac.uk/efo/EFO_0000635] Value=organism part [http://www.ebi.ac.uk/efo/EFO_0000635] in split 1, leaving 1 fvs still used
2024-10-24 11:26:25,508 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(243) | 2 unused factor values removed for ExperimentalFactor Name=collection of material Type=CATEGORICAL Category=Characteristic Category=collection of material [http://www.ebi.ac.uk/efo/EFO_0005066] Value=collection of material [http://www.ebi.ac.uk/efo/EFO_0005066] in split 1, leaving 0 fvs still used
2024-10-24 11:26:25,508 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(269) | 2 unused experimental factors dropped from split 1
2024-10-24 11:26:25,508 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(272) | Building vectors for 3 quantitation types ...
2024-10-24 11:26:25,732 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(292) | GSE123919.1: Adding 35205 raw data vectors for QuantitationType Name=Counts General Type=QUANTITATIVE Type=COUNT Scale=COUNT Representation=DOUBLE [Recomputed From Raw] [Preferred] preferred=false
2024-10-24 11:26:25,833 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(292) | GSE123919.1: Adding 35205 raw data vectors for QuantitationType Name=RPKM General Type=QUANTITATIVE Type=AMOUNT Scale=LINEAR Representation=DOUBLE [Normalized] [Recomputed From Raw] [Preferred] preferred=false
2024-10-24 11:26:25,925 INFO 1013781 [main] u.g.c.a.p.SplitExperimentServiceImpl.split(292) | GSE123919.1: Adding 35205 raw data vectors for QuantitationType Name=log2cpm General Type=QUANTITATIVE Type=AMOUNT Scale=LOG2 Representation=DOUBLE [Recomputed From Raw] [Preferred] preferred=true
2024-10-24 11:26:25,967 WARN 1013781 [main] u.g.p.p.ExpressionPersister.doPersist(139) | Consider doing the 'prepare' step in a separate transaction.
2024-10-24 11:26:28,447 INFO 1013781 [main] u.g.p.p.ExpressionPersister.checkExperimentalDesign(181) | Checking: ExperimentalFactor Id=59456 Name=treatment Type=CATEGORICAL Category=Characteristic Id=39110663 Category=treatment [http://www.ebi.ac.uk/efo/EFO_0000727] Value=treatment [http://www.ebi.ac.uk/efo/EFO_0000727], 2 factor values to check...
2024-10-24 11:26:28,473 ERROR 1013781 [main] u.g.c.u.AbstractCLI.executeCommand(236) | splitExperiment failed: IllegalArgumentException: Cannot create an already persistent entity.
java.lang.IllegalArgumentException: Cannot create an already persistent entity.
        at org.springframework.util.Assert.isNull(Assert.java:89) ~[spring-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at ubic.gemma.persistence.service.AbstractDao.create(AbstractDao.java:109) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.service.expression.experiment.FactorValueDaoImpl.create(FactorValueDaoImpl.java:63) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.service.expression.experiment.FactorValueDaoImpl.create(FactorValueDaoImpl.java:51) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.service.AbstractDao.findOrCreate(AbstractDao.java:357) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.service.AbstractDao.findOrCreate(AbstractDao.java:50) ~[gemma-core-1.31.12.jar:?]
        ... suppressed 15 lines
        at ubic.gemma.persistence.persister.ExpressionPersister.persistFactorValue(ExpressionPersister.java:429) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.fillInBioAssayAssociations(ExpressionPersister.java:252) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.persistBioAssay(ExpressionPersister.java:353) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.persistBioAssayDimension(ExpressionPersister.java:363) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.getBioAssayDimensionFromCacheOrCreate(ExpressionPersister.java:343) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.fillInDesignElementDataVectorAssociations(ExpressionPersister.java:277) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.fillInExpressionExperimentDataVectorAssociations(ExpressionPersister.java:301) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.processBioAssays(ExpressionPersister.java:444) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.persistExpressionExperiment(ExpressionPersister.java:122) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.doPersist(ExpressionPersister.java:142) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.RelationshipPersister.doPersist(RelationshipPersister.java:59) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.PersisterHelperImpl.doPersist(PersisterHelperImpl.java:43) ~[gemma-core-1.31.12.jar:?]
        at ubic.gemma.persistence.persister.AbstractPersister.persist(AbstractPersister.java:100) ~[gemma-core-1.31.12.jar:?]
        ... suppressed 24 lines
        at ubic.gemma.core.analysis.preprocess.SplitExperimentServiceImpl.split(SplitExperimentServiceImpl.java:297) ~[gemma-core-1.31.12.jar:?]
        ... suppressed 11 lines
        at ubic.gemma.core.apps.SplitExperimentCli.doWork(SplitExperimentCli.java:107) ~[gemma-cli-1.31.12.jar:?]
        at ubic.gemma.core.util.AbstractCLI.executeCommand(AbstractCLI.java:209) [gemma-cli-1.31.12.jar:?]
        at ubic.gemma.core.apps.GemmaCLI.main(GemmaCLI.java:288) [gemma-cli-1.31.12.jar:?]
========= Gemma CLI run of splitExperiment complete in 12 seconds ============
```

**Comment by arteymix** [comment]
Will address this immediately because it prevents splitting a single-cell dataset.

**Comment by arteymix** [comment]
The issue is fixed and will be deployed soon. Use `gemma-cli-staging` to split this experiment.
