### ISSUE TITLE
Failure to always detect when interactions can't be estimated

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#157]
`Note: java.lang.IllegalArgumentException: Column name cannot be null at ubic.basecode.dataStructure.matrix.AbstractMatrix.addColumnName(AbstractMatrix.java:69) at ubic.basecode.math.linearmodels.DesignMatrix.addInteraction(DesignMatrix.java:243) at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer.makeDesignMatrix(LinearModelAnalyzer.java:1236) at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer.doAnalysis(LinearModelAnalyzer.java:708) at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer.run(LinearModelAnalyzer.java:488) at ubic.gemma.core.analysis.expression.diff.LinearModelAnalyzer.run(LinearModelAnalyzer.java:381) at sun.reflect.GeneratedMethodAccessor2708.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) at com.sun.proxy.$Proxy448.run(Unknown Source) at ubic.gemma.core.analysis.expression.diff.AnalysisSelectionAndExecutionServiceImpl.analyze(AnalysisSelectionAndExecutionServiceImpl.java:63) at sun.reflect.GeneratedMethodAccessor2707.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) at com.sun.proxy.$Proxy162.analyze(Unknown Source) at ubic.gemma.core.analysis.expression.diff.DifferentialExpressionAnalyzerServiceImpl.runDifferentialExpressionAnalyses(DifferentialExpressionAnalyzerServiceImpl.java:177) at sun.reflect.GeneratedMethodAccessor2711.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) at com.sun.proxy.$Proxy164.runDifferentialExpressionAnalyses(Unknown Source) at ubic.gemma.core.tasks.analysis.diffex.DifferentialExpressionAnalysisTaskImpl.doAnalysis(DifferentialExpressionAnalysisTaskImpl.java:141) at ubic.gemma.core.tasks.analysis.diffex.DifferentialExpressionAnalysisTaskImpl.execute(DifferentialExpressionAnalysisTaskImpl.java:77) at sun.reflect.GeneratedMethodAccessor2405.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) at com.sun.proxy.$Proxy447.execute(Unknown Source) at ubic.gemma.core.job.executor.common.ExecutingTask.call(ExecutingTask.java:55) at ubic.gemma.core.job.executor.common.ExecutingTask.call(ExecutingTask.java:29) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
`

See https://github.com/PavlidisLab/GemmaCuration/issues/131

**Comment by ppavlidis** [comment]
This was due to insufficient checks for a valid interaction term, which was showing up as problems especially when doing subsets, which tend to leave not enough replication. Another manifestation is "No residual degrees of freedom to fit the model". The actual issue resides in baseCode's DesignMatrix.
