### ISSUE TITLE
Could not load [com.hp.hpl.jena.graph.GraphUtil]

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#190]
The main outcome is that most TGEMO terms are no longer searchable (according to @Tu1026). 

I still suspect this is due to some threads still running when restarting. Details here: https://stackoverflow.com/questions/4945153/illegal-access-this-web-application-instance-has-been-stopped-already I might try to restart and kill any remaining Gemma processes tonight.

It also started happening after the Unicode migration of the database, so it might be worth to review the code and attempt to reproduce this issue separately.

Here's the stack trace from Tomcat:

```
org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.hp.hpl.jena.graph.GraphUtil]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.hp.hpl.jena.graph.GraphUtil]. The following stack trace is thrown for debugging purposes as well as to attempt t
o terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1378)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1366)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1218)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
        at com.hp.hpl.jena.graph.impl.GraphBase.graphBaseSize(GraphBase.java:410)
        at com.hp.hpl.jena.graph.impl.GraphBase.size(GraphBase.java:383)
        at com.hp.hpl.jena.graph.impl.GraphBase.isEmpty(GraphBase.java:430)
        at com.hp.hpl.jena.reasoner.BaseInfGraph.isEmpty(BaseInfGraph.java:447)
        at com.hp.hpl.jena.rdf.model.impl.ModelCom.isEmpty(ModelCom.java:871)
        at ubic.basecode.ontology.OntologyLoader.loadMemoryModel(OntologyLoader.java:261)
        at ubic.basecode.ontology.OntologyLoader.loadMemoryModel(OntologyLoader.java:173)
        at ubic.basecode.ontology.providers.AbstractOntologyMemoryBackedService.loadModel(AbstractOntologyMemoryBackedService.java:95)
        at ubic.basecode.ontology.providers.AbstractOntologyService.getModel(AbstractOntologyService.java:438)
        at ubic.basecode.ontology.providers.AbstractOntologyService$OntologyInitializationThread.run(AbstractOntologyService.java:97)
```

**Comment by Tu1026** [comment]
After some more spot testing, it seems like most if not all TGEMO terms work except the study design tags, or more specifically the ontology terms that have square brackets such as [Sample Study], [Benchmark Study], [Time Consuming], and more.

**Comment by arteymix** [comment]
@Tu1026 Is this problem still affecting the production Gemma?

**Comment by Tu1026** [comment]
Yes I just tested and I still cannot tag TGEMO terms like [Sample Study] and other ones

**Comment by arteymix** [comment]
Okay, I'll try to reproduce and fix this problem tomorrow.

**Comment by arteymix** [comment]
I found this in gemma logs:

```
[Gemma - fmaOntology_load_thread_GCaEy (2021-10-04 12:19:14,541)] ERROR ubic.basecode.ontology.providers.AbstractOntologyService$OntologyInitializationThread.run(131) | Indexing failure for fmaOntology
java.lang.RuntimeException: Indexing failure for fmaOntology
        at ubic.basecode.ontology.search.OntologyIndexer.index(OntologyIndexer.java:200)
        at ubic.basecode.ontology.search.OntologyIndexer.indexOntology(OntologyIndexer.java:85)
        at ubic.basecode.ontology.providers.AbstractOntologyService.index(AbstractOntologyService.java:345)
        at ubic.basecode.ontology.providers.AbstractOntologyService$OntologyInitializationThread.run(AbstractOntologyService.java:104)
Caused by: java.io.IOException: Cannot create directory: /home/poirigui/ontology.index.dir/ontology/fmaOntology
        at org.apache.lucene.store.NativeFSLock.obtain(NativeFSLockFactory.java:171)
        at org.apache.lucene.store.Lock.obtain(Lock.java:72)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1098)
        at ubic.basecode.ontology.search.OntologyIndexer.index(OntologyIndexer.java:176)
        ... 3 more
```

It seems that Gemma resolves the ontology directory relative to my home directory...

**Comment by ppavlidis** [comment]
that should be part of the Gemma.properties file configuration

**Comment by arteymix** [comment]
I think Tomcat is picking up my `Gemma.properties`. I'll restart Gemma with a clean env. @dima-v-v should look into setting up the systemd unit on moe so that we don't have this problem anymore.

**Comment by arteymix** [comment]
The issue has been resolved. Once we switch to systemd, it should not occur again.
