### ISSUE TITLE
Data truncation: Data too long for column 'BATCH_CONFOUND' at row 1

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#236]
We need to make that column longer.

```
ERROR ubic.gemma.core.job.executor.webapp.TaskRunningServiceImpl$1.onFailure(116) | java.lang.IllegalStateException: ubic.gemma.core.analysis.preprocess.PreprocessingException: org.spri
ngframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [update INVESTIGATION set AUDIT_TRAIL_FK=?, NAME=?, DESCRIPTION=?, OWNER_FK=?, PRIMARY_PUBLICATION_FK=?, SOURCE=?, SHORT_NAME=?, NUMBER_OF_DATA_VECT
ORS=?, NUMBER_OF_SAMPLES=?, METADATA=?, BATCH_EFFECT=?, BATCH_CONFOUND=?, GEEQ_FK=?, ACCESSION_FK=?, EXPERIMENTAL_DESIGN_FK=?, TAXON_FK=?, MEAN_VARIANCE_RELATION_FK=?, CURATION_DETAILS_FK=? where ID=?]; nested exception is org.hibernate.e
xception.DataException: Could not execute JDBC batch update
java.lang.IllegalStateException: ubic.gemma.core.analysis.preprocess.PreprocessingException: org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [update INVESTIGATION set AUDIT_TRAIL_FK=?, NAM
E=?, DESCRIPTION=?, OWNER_FK=?, PRIMARY_PUBLICATION_FK=?, SOURCE=?, SHORT_NAME=?, NUMBER_OF_DATA_VECTORS=?, NUMBER_OF_SAMPLES=?, METADATA=?, BATCH_EFFECT=?, BATCH_CONFOUND=?, GEEQ_FK=?, ACCESSION_FK=?, EXPERIMENTAL_DESIGN_FK=?, TAXON_FK=?
, MEAN_VARIANCE_RELATION_FK=?, CURATION_DETAILS_FK=? where ID=?]; nested exception is org.hibernate.exception.DataException: Could not execute JDBC batch update
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:75)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy206.process(Unknown Source)
        at ubic.gemma.core.analysis.service.OutlierFlaggingServiceImpl.markAsMissing(OutlierFlaggingServiceImpl.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy237.markAsMissing(Unknown Source)
        at ubic.gemma.core.tasks.analysis.expression.BioAssayOutlierProcessingTaskImpl.execute(BioAssayOutlierProcessingTaskImpl.java:42)
        at sun.reflect.GeneratedMethodAccessor1478.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy446.execute(Unknown Source)
        at ubic.gemma.core.job.executor.common.ExecutingTask.call(ExecutingTask.java:55)
        at ubic.gemma.core.job.executor.common.ExecutingTask.call(ExecutingTask.java:29)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by arteymix** [comment]
I promoted the type to a `TEXT` which can hold up to 65kb of text data. If that is not sufficient, I don't think the solution would reside in making the field larger.

**Comment by arteymix** [comment]
I had to cancel the database alter statement because it was taking too long.

```
alter table INVESTIGATION
    modify column BATCH_CONFOUND text,
    modify column BATCH_EFFECT text;
````

**Comment by arteymix** [comment]
This could show useful https://dev.mysql.com/doc/refman/5.7/en/monitor-alter-table-performance-schema.html to monitor the progress of the statements.

**Comment by arteymix** [comment]
It seems that this issue (as well as #212) was caused by a deadlock with a long-running MySQL process.
