### ISSUE TITLE
Search error on settings: IBD [human]; message=java.lang.NoSuchMethodException: java.util.HashSet.getId()

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#244]
```
ERROR ubic.gemma.core.search.SearchServiceImpl.search(256) | Search error on settings: IBD [human]; message=java.lang.NoSuchMethodException: java.util.HashSet.getId()
java.lang.RuntimeException: java.lang.NoSuchMethodException: java.util.HashSet.getId()
        at ubic.gemma.persistence.util.EntityUtils.getId(EntityUtils.java:103)
        at ubic.gemma.persistence.util.EntityUtils.getId(EntityUtils.java:94)
        at ubic.gemma.persistence.util.EntityUtils.getIds(EntityUtils.java:186)
        at ubic.gemma.core.search.SearchServiceImpl.filterExperimentHitsByTaxon(SearchServiceImpl.java:391)
        at ubic.gemma.core.search.SearchServiceImpl.compassExpressionSearch(SearchServiceImpl.java:1015)
        at ubic.gemma.core.search.SearchServiceImpl.expressionExperimentSearch(SearchServiceImpl.java:1634)
        at ubic.gemma.core.search.SearchServiceImpl.accreteResultsOthers(SearchServiceImpl.java:447)
        at ubic.gemma.core.search.SearchServiceImpl.generalSearch(SearchServiceImpl.java:1880)
        at ubic.gemma.core.search.SearchServiceImpl.search(SearchServiceImpl.java:297)
        at ubic.gemma.core.search.SearchServiceImpl.search(SearchServiceImpl.java:250)
        at sun.reflect.GeneratedMethodAccessor1303.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy118.search(Unknown Source)
        at ubic.gemma.core.expression.experiment.service.ExpressionExperimentSearchServiceImpl.initialSearch(ExpressionExperimentSearchServiceImpl.java:303)
        at ubic.gemma.core.expression.experiment.service.ExpressionExperimentSearchServiceImpl.searchExperimentsAndExperimentGroups(ExpressionExperimentSearchServiceImpl.java:133)
        at sun.reflect.GeneratedMethodAccessor2359.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy240.searchExperimentsAndExperimentGroups(Unknown Source)
        at ubic.gemma.web.controller.expression.experiment.ExpressionExperimentController.searchExperimentsAndExperimentGroups(ExpressionExperimentController.java:854)
        at ubic.gemma.web.controller.expression.experiment.ExpressionExperimentController$$FastClassBySpringCGLIB$$9cc9e2f2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
        at ubic.gemma.web.controller.expression.experiment.ExpressionExperimentController$$EnhancerBySpringCGLIB$$ad0e9355.searchExperimentsAndExperimentGroups(<generated>)
        at sun.reflect.GeneratedMethodAccessor2357.invoke(Unknown Source)
```

**Comment by arteymix** [comment]
Fixed in b9054310ba400d894f2889ee1834893a788b68d8, this is a duplicate of #330
