### ISSUE TITLE
Error while searching: Error during search for 'Psen1 AND +;

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#245]
It looks like a SQL injection attempt. This error should be handled properly though and produce a bad request response status.

```
ERROR ubic.basecode.ontology.search.OntologySearch.runSearch(331) | Error while searching: Error during search for 'Psen1 AND +;
org.apache.jena.larq.ARQLuceneException: Error during search for 'Psen1 AND +;
        at ubic.basecode.ontology.search.SearchIndex.search(SearchIndex.java:73)
        at org.apache.jena.larq.IndexLARQ.searchModelByIndex(IndexLARQ.java:140)
        at org.apache.jena.larq.IndexLARQ.searchModelByIndex(IndexLARQ.java:121)
        at org.apache.jena.larq.IndexLARQ.searchModelByIndex(IndexLARQ.java:110)
        at ubic.basecode.ontology.search.OntologySearch.runSearch(OntologySearch.java:322)
        at ubic.basecode.ontology.search.OntologySearch.matchResources(OntologySearch.java:211)
        at ubic.basecode.ontology.providers.AbstractOntologyService.findResources(AbstractOntologyService.java:229)
        at ubic.gemma.core.ontology.OntologyServiceImpl.findTermsInexact(OntologyServiceImpl.java:412)
        at sun.reflect.GeneratedMethodAccessor2429.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy120.findTermsInexact(Unknown Source)
        at ubic.gemma.web.controller.expression.experiment.AnnotationController.findTerm(AnnotationController.java:117)
        at ubic.gemma.web.controller.expression.experiment.AnnotationController$$FastClassBySpringCGLIB$$75c5e2c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
        at ubic.gemma.web.controller.expression.experiment.AnnotationController$$EnhancerBySpringCGLIB$$26d9714f.findTerm(<generated>)
        at sun.reflect.GeneratedMethodAccessor2428.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.directwebremoting.impl.ExecuteAjaxFilter.doFilter(ExecuteAjaxFilter.java:34)
        at org.directwebremoting.impl.DefaultRemoter$1.doFilter(DefaultRemoter.java:428)
        at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:431)
        at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:283)
        at org.directwebremoting.servlet.PlainCallHandler.handle(PlainCallHandler.java:52)
        at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:101)
        at org.directwebremoting.spring.DwrController.handleRequestInternal(DwrController.java:234)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
```

**Comment by arteymix** [comment]
This need to be caught and bubble up to the input form to notify the user.

We've had another case recently:

```
ARQLuceneException: Error during search for 'Dmpk AND *;
```org.apache.jena.larq.ARQLuceneException: Error during search for 'Dmpk AND *;
    at ubic.basecode.ontology.search.SearchIndex.search(SearchIndex.java:73)
    at org.apache.jena.larq.IndexLARQ.searchModelByIndex(IndexLARQ.java:140)
    at org.apache.jena.larq.IndexLARQ.searchModelByIndex(IndexLARQ.java:121)
    at org.apache.jena.larq.IndexLARQ.searchModelByIndex(IndexLARQ.java:110)
```

**Comment by arteymix** [comment]
Basecode needs to be modified to have a proper exception hierarchy that can be handled by the caller.

**Comment by arteymix** [comment]
https://github.com/PavlidisLab/baseCode/issues/16

**Comment by arteymix** [comment]
Ok, it's almost complete. The search service converts those to SearchException which we already handle in the majority of cases on the front-end side.

**Comment by arteymix** [comment]
This should be fixed now.
