### ISSUE TITLE
Search error on settings: brain; message=null java.lang.NullPointerException

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#247]
```
ERROR ubic.gemma.core.search.SearchServiceImpl.search(236) | Search error on settings: brain; message=null
java.lang.NullPointerException
        at ubic.basecode.ontology.model.OntologyTermImpl.getChildren(OntologyTermImpl.java:389)
        at ubic.basecode.ontology.model.OntologyTermImpl.getChildren(OntologyTermImpl.java:130)
        at ubic.gemma.core.search.SearchServiceImpl.getDirectChildTerms(SearchServiceImpl.java:2069)
        at ubic.gemma.core.search.SearchServiceImpl.getCharacteristicsAnnotatedToChildren(SearchServiceImpl.java:2019)
        at ubic.gemma.core.search.SearchServiceImpl.characteristicEESearchTerm(SearchServiceImpl.java:816)
        at ubic.gemma.core.search.SearchServiceImpl.characteristicEESearchWithChildren(SearchServiceImpl.java:911)
        at ubic.gemma.core.search.SearchServiceImpl.characteristicEESearch(SearchServiceImpl.java:723)
        at ubic.gemma.core.search.SearchServiceImpl.expressionExperimentSearch(SearchServiceImpl.java:1630)
        at ubic.gemma.core.search.SearchServiceImpl.accreteResultsOthers(SearchServiceImpl.java:455)
        at ubic.gemma.core.search.SearchServiceImpl.generalSearch(SearchServiceImpl.java:1888)
        at ubic.gemma.core.search.SearchServiceImpl.search(SearchServiceImpl.java:283)
        at ubic.gemma.core.search.SearchServiceImpl.search(SearchServiceImpl.java:230)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy112.search(Unknown Source)
        at ubic.gemma.web.controller.GeneralSearchControllerImpl.ajaxSearch(GeneralSearchControllerImpl.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by arteymix** [comment]
This seems to be a specific issue for brain term, cancer search works. It looks like a bug in baseCode.

**Comment by arteymix** [comment]
The error is caused by a null URI. I'm not sure what it means, but Jena documentation mentions it happens if the term is a bnode.

**Comment by arteymix** [comment]
I'll test the fix in baseCode and create a hotfix release if it resolves the search issue.
