### ISSUE TITLE
MeanVarianceServiceTest fails (probably due to new filtering logics)

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#264]
Logs from the CI:

```
13:05:05 [ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 87.502 s <<< FAILURE! - in ubic.gemma.core.analysis.preprocess.MeanVarianceServiceTest
13:05:05 [ERROR] testServiceCreateTwoColor(ubic.gemma.core.analysis.preprocess.MeanVarianceServiceTest)  Time elapsed: 13.338 s  <<< FAILURE!
13:05:05 java.lang.AssertionError: expected:<75> but was:<72>
13:05:05 	at ubic.gemma.core.analysis.preprocess.MeanVarianceServiceTest.testServiceCreateTwoColor(MeanVarianceServiceTest.java:148)
13:05:05 
13:05:05 [ERROR] testServiceCreateOneColor(ubic.gemma.core.analysis.preprocess.MeanVarianceServiceTest)  Time elapsed: 13.056 s  <<< FAILURE!
13:05:05 java.lang.AssertionError: expected:<75> but was:<72>
13:05:05 	at ubic.gemma.core.analysis.preprocess.MeanVarianceServiceTest.testServiceCreateOneColor(MeanVarianceServiceTest.java:193)

**Comment by arteymix** [comment]
This test is also affected:

```
13:15:26 [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.041 s <<< FAILURE! - in ubic.gemma.core.analysis.expression.diff.TTestAnalyzerTest
13:15:26 [ERROR] testOneSampleTtest(ubic.gemma.core.analysis.expression.diff.TTestAnalyzerTest)  Time elapsed: 1.022 s  <<< FAILURE!
13:15:26 java.lang.AssertionError: expected:<96> but was:<100>
13:15:26 	at ubic.gemma.core.analysis.expression.diff.TTestAnalyzerTest.testOneSampleTtest(TTestAnalyzerTest.java:90)
13:15:26 
```
