### ISSUE TITLE
<AST>:0:0: unexpected end of subtree

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#327]
I'm not sure exactly where this is occurring, but we have a syntax issue with one of our query. This is similar to #81.

```
[Gemma - http-nio-8181-exec-7 (2022-04-02 21:39:59,838)] ERROR org.hibernate.hql.ast.ErrorCounter.reportError(56) | <AST>:0:0: unexpected end of subtree
```

Not much details, but I think we can cross-reference the time with debug logs.

**Comment by arteymix** [comment]
I wonder if it could be related to this:

```
[Gemma - http-nio-8181-exec-6 (2022-04-04 11:22:08,851)] ERROR ubic.basecode.ontology.search.OntologySearch.runSearch(331) | Error while searching: Error during search for 'BRCA!*;
ARQLuceneException: Error during search for 'BRCA!*;
org.apache.jena.larq.ARQLuceneException: Error during search for 'BRCA!*;
    at ubic.basecode.ontology.search.SearchIndex.search(SearchIndex.java:73)
    at org.apache.jena.larq.IndexLARQ.searchModelByIndex(IndexLARQ.java:140)
    at org.apache.jena.larq.IndexLARQ.searchModelByIndex(IndexLARQ.java:121)
    at org.apache.jena.larq.IndexLARQ.searchModelByIndex(IndexLARQ.java:110)
```

Basically, we can't use a `!` in the search, or maybe only preceeding an expression?

**Comment by arteymix** [comment]
ARQException are handled, but not ARQLuceneException. I'll add a catch clause.

**Comment by arteymix** [comment]
Ok, I figured it out.

It's an empty collection passed as a parameter to this query:
:
```
[Gemma - http-nio-8181-exec-211 (2022-04-18 13:28:28,797)] WARN org.directwebremoting.util.CommonsLoggingOutput.warn(67) | Method execution failed: 
org.hibernate.hql.ast.QuerySyntaxException: unexpected end of subtree [select ee, ad, op, ee.bioAssays.size from ubic.gemma.model.expression.experiment.ExpressionExperiment as ee join ee.bioAssays ba join ba.arrayDesignUsed ad left join b
a.originalPlatform op where ee in () group by ee, ad, op]
 of subtree
```
