### ISSUE TITLE
Sporadic "Access denied" while performing sequence analysis or gene mapping of platforms

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#389]
The following platforms have to be reviewed for potential ACL-related issues:

```
GPL10117
GPL10907
GPL1211
GPL13667
GPL14550
GPL15496
GPL15789
GPL16043
GPL16699
GPL16876
GPL17077
GPL18734
GPL19137
GPL19197
GPL20844
GPL21185
GPL22382
GPL23126
GPL24170
GPL3313
GPL4191
GPL5639
GPL6665
GPL6729
GPL8128
```

**Comment by ppavlidis** [comment]
These platforms don't have ACL issues. There is some other problem that sporadically causes "access denied" while performing sequence analysis or gene mapping of platforms; it will eventually work after attempting again. 

Furthermore this happens in the midst of processing a platform, the platform has already been accessed successfully. Feels like a race condition.

```
2022-07-16 00:15:00,076 ^[[1;31mERROR^[[m ^[[35m10718^[[m [taskExecutor-1] ^[[36mubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl.doLoad(461)^[[m | org.springframework.security.access.AccessDeniedException: Access is denied
org.springframework.security.access.AccessDeniedException: Access is denied
        at org.springframework.security.access.vote.UnanimousBased.decide(UnanimousBased.java:90) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:206) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:60) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy131.persist(Unknown Source) ~[?:?]
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl.doLoad(ArrayDesignProbeMapperServiceImpl.java:449) ~[gemma-core-1.28.0-SNAPSHOT.jar:?]
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl.access$000(ArrayDesignProbeMapperServiceImpl.java:77) ~[gemma-core-1.28.0-SNAPSHOT.jar:?]
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl$1.run(ArrayDesignProbeMapperServiceImpl.java:521) ~[gemma-core-1.28.0-SNAPSHOT.jar:?]
        at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:81) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_302]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_302]
Exception in thread "taskExecutor-1" java.lang.RuntimeException: org.springframework.security.access.AccessDeniedException: Access is denied
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl.doLoad(ArrayDesignProbeMapperServiceImpl.java:463)
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl.access$000(ArrayDesignProbeMapperServiceImpl.java:77)
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl$1.run(ArrayDesignProbeMapperServiceImpl.java:521)
        at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.security.access.AccessDeniedException: Access is denied
        at org.springframework.security.access.vote.UnanimousBased.decide(UnanimousBased.java:90)
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:206)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:60)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy131.persist(Unknown Source)
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl.doLoad(ArrayDesignProbeMapperServiceImpl.java:449)
        ... 6 more
```

**Comment by ppavlidis** [comment]
Managed to get debug logging of an incidence

```
2022-08-01 00:15:00,046 ^[[36mDEBUG^[[m ^[[35m48227^[[m [schedulerFactoryBean_Worker-2] ^[[36morg.springframework.security.access.vote.UnanimousBased.decide(80)^[[m | Voter: gemma.gsec.acl.voter.AclCollectionEntryVoter@590f806a, returned: 0
2022-08-01 00:15:00,046 ^[[36mDEBUG^[[m ^[[35m48227^[[m [schedulerFactoryBean_Worker-2] ^[[36morg.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(215)^[[m | Authorization successful
2022-08-01 00:15:00,046 ^[[36mDEBUG^[[m ^[[35m48227^[[m [schedulerFactoryBean_Worker-2] ^[[36morg.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(227)^[[m | RunAsManager did not change Authentication object
2022-08-01 00:15:00,117 ^[[36mDEBUG^[[m ^[[35m48227^[[m [taskExecutor-1] ^[[36morg.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(194)^[[m | Secure object: ReflectiveMethodInvocation: public abstract java.lang.Object ubic.gemma.persistence.persister.Persister.persist(java.lang.Object); target is of class [ubic.gemma.persistence.persister.PersisterHelper]; Attributes: [GROUP_USER]
2022-08-01 00:15:00,117 ^[[36mDEBUG^[[m ^[[35m48227^[[m [taskExecutor-1] ^[[36morg.springframework.security.access.intercept.AbstractSecurityInterceptor.authenticateIfRequired(310)^[[m | Previously Authenticated: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@5ae2d8c1: Principal: gemmaAgent; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: GROUP_AGENT
2022-08-01 00:15:00,117 ^[[36mDEBUG^[[m ^[[35m48227^[[m [taskExecutor-1] ^[[36morg.springframework.security.access.vote.UnanimousBased.decide(80)^[[m | Voter: gemma.gsec.acl.voter.AclEntryVoter@7e35d743, returned: 0
2022-08-01 00:15:00,117 ^[[36mDEBUG^[[m ^[[35m48227^[[m [taskExecutor-1] ^[[36morg.springframework.security.access.vote.UnanimousBased.decide(80)^[[m | Voter: gemma.gsec.acl.voter.AclEntryVoter@63b2418e, returned: 0
2022-08-01 00:15:00,117 ^[[36mDEBUG^[[m ^[[35m48227^[[m [taskExecutor-1] ^[[36morg.springframework.security.access.hierarchicalroles.RoleHierarchyImpl.getReachableGrantedAuthorities(117)^[[m | getReachableGrantedAuthorities() - From the roles [GROUP_AGENT] one can reach [GROUP_ANONYMOUS, GROUP_AGENT, IS_AUTHENTICATED_ANONYMOUSLY] in zero or more steps.
2022-08-01 00:15:00,117 ^[[36mDEBUG^[[m ^[[35m48227^[[m [taskExecutor-1] ^[[36morg.springframework.security.access.vote.UnanimousBased.decide(80)^[[m | Voter: org.springframework.security.access.vote.RoleHierarchyVoter@70d16858, returned: -1
2022-08-01 00:15:00,118 ^[[1;31mERROR^[[m ^[[35m48227^[[m [taskExecutor-1] ^[[36mubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl.doLoad(461)^[[m | org.springframework.security.access.AccessDeniedException: Access is denied
org.springframework.security.access.AccessDeniedException: Access is denied
        at org.springframework.security.access.vote.UnanimousBased.decide(UnanimousBased.java:90) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:206) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:60) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy74.persist(Unknown Source) ~[?:?]
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl.doLoad(ArrayDesignProbeMapperServiceImpl.java:449) ~[gemma-core-1.28.0-SNAPSHOT.jar:?]
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl.access$000(ArrayDesignProbeMapperServiceImpl.java:77) ~[gemma-core-1.28.0-SNAPSHOT.jar:?]
        at ubic.gemma.core.loader.expression.arrayDesign.ArrayDesignProbeMapperServiceImpl$1.run(ArrayDesignProbeMapperServiceImpl.java:521) ~[gemma-core-1.28.0-SNAPSHOT.jar:?]
        at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:81) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_302]

```

**Comment by ppavlidis** [comment]
I noticed that these errors seem to happen several times "in a row" (on platforms being sequentially analyzed). But other times I don't see it at all. 

In other words, once it starts happening, it seems to recur. It tends not to happen just once.

**Comment by ppavlidis** [comment]
Also happens with differential expression analysis CLI.

**Comment by ppavlidis** [comment]
Is it possible this is due to a Quartz task (cron) that is running in the background? Those use GROUP_AGENT.

But I thought Quartz was disabled for command lines. We don't want cron tasks like updating reports to be triggered by routine command lines that happen to be running at the appropriate time of day.

**Comment by arteymix** [comment]
Are you getting these errors from the CLI? Does that mean that the Quartz scheduler is running in the background?

**Comment by arteymix** [comment]
It would make a lot of sense to get sporadic errors if it's caused by a background job running with a different user but polluting your main task logs. I'll investigate if it is running...

**Comment by ppavlidis** [comment]
This is all with the CLI, as described above. Like I said I thought we already were shutting Quartz down when the CLI launches, but maybe not.

There is no logging I've seen that indicates any background process running when these failures happen, though.

**Comment by ppavlidis** [comment]
In the last occurrence, there was a failure at 12:12PM, several successful jobs, and failure again at 3:30PM after which it recurred for every experiment being processed. I don't think we have cron tasks going off at/near those times.

**Comment by arteymix** [comment]
But still, the `gemmaAgent` had to be authenticated at some point, otherwise it wouldn't show up in logs. Can you try adding a breakpoint conditional on the principal and get a backtrace from there?

**Comment by ppavlidis** [comment]
I won't have time to do that until later this month. Remember it happens sporadically and doing hundreds of jobs over a tunnel in a debugger, while waiting for an error that might not occur, is going to be painful.

**Comment by arteymix** [comment]
Ok, I'll investigate where that gemmaAgent could have dispatched a callable.

**Comment by arteymix** [comment]
Follow-up will be in https://github.com/PavlidisLab/Gemma/issues/399.
