### ISSUE TITLE
IllegalArgumentException: Vectors must be provided when obtaining filtered data via the API

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#408]
From the logs:

> [Gemma - http-nio-8181-exec-816 (2022-08-09 03:28:42,938)] ERROR ubic.gemma.web.services.rest.providers.UnhandledExceptionMapper.toResponse(35) | Unhandled exception was raised for GET /rest/v2/datasets/GSE47900/data?filter=true.

```
IllegalArgumentException: Vectors must be provided
```java.lang.IllegalArgumentException: Vectors must be provided
    at ubic.gemma.core.analysis.service.ExpressionDataMatrixServiceImpl.getFilteredMatrix(ExpressionDataMatrixServiceImpl.java:176)
    at ubic.gemma.core.analysis.service.ExpressionDataMatrixServiceImpl.getFilteredMatrix(ExpressionDataMatrixServiceImpl.java:80)
    at ubic.gemma.core.analysis.service.ExpressionDataMatrixServiceImpl.getFilteredMatrix(ExpressionDataMatrixServiceImpl.java:73)
    at sun.reflect.GeneratedMethodAccessor16704.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy3411.getFilteredMatrix(Unknown Source)
    at ubic.gemma.core.analysis.service.ExpressionDataFileServiceImpl.getDataMatrix(ExpressionDataFileServiceImpl.java:736)
    at ubic.gemma.core.analysis.service.ExpressionDataFileServiceImpl.writeDataFile(ExpressionDataFileServiceImpl.java:1085)
    at ubic.gemma.core.analysis.service.ExpressionDataFileServiceImpl.writeOrLocateDataFile(ExpressionDataFileServiceImpl.java:401)
    at sun.reflect.GeneratedMethodAccessor16224.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy3419.writeOrLocateDataFile(Unknown Source)
    at ubic.gemma.web.services.rest.DatasetsWebService.outputDataFile(DatasetsWebService.java:479)
    at ubic.gemma.web.services.rest.DatasetsWebService.datasetData(DatasetsWebService.java:255)
    at ubic.gemma.web.services.rest.DatasetsWebService$$FastClassBySpringCGLIB$$be285e32.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
    at ubic.gemma.web.services.rest.DatasetsWebService$$EnhancerBySpringCGLIB$$6da13a3d.datasetData(<generated>)
    at sun.reflect.GeneratedMethodAccessor16225.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    a…
```

**Comment by ppavlidis** [comment]
Still applies in 2.0-alpha; needs focused follow-up. Audited during 2.0-alpha bug triage. `ExpressionDataMatrixServiceImpl.getFilteredMatrix` still throws `IllegalArgumentException: Vectors must be provided` for some datasets accessed via `/datasets/{id}/data?filter=true`. The code path remains live and needs a defensive check before invoking the matrix constructor.

**Comment by ppavlidis** [comment]
Fix in commit `9503d8abfd` on branch `agent-rest-polish` (will be merged to `phase2-acl-migrate`).

The private `ExpressionDataMatrixServiceImpl.getFilteredMatrix` overload now throws `NoDesignElementsException` (a `FilteringException` subclass) instead of `IllegalArgumentException` when the supplied vector collection is empty. `DatasetsWebService` already catches `NoDesignElementsException` around the streaming response writer (`DatasetsWebService.java:4290`) and degrades gracefully to an empty body, so this routes the failure through the existing handler instead of leaking a 500 from `UnhandledExceptionMapper`.

**Comment by ppavlidis** [comment]
Gemma 2 disposition: Fixed

**Comment by ppavlidis** [comment]
Fix landed in https://github.com/PavlidisLab/Gemma/commit/9503d8abfd
