### ISSUE TITLE
Can't connect to X11 window server using 'localhost:13.0' as the value of the DISPLAY variable

### ISSUE THREAD

**Issue by sanjarogic** [PavlidisLab/Gemma#492]
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:13.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:131)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2041)
	at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1158)
	at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:431)
	at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
	at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:579)
	at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1349)
	at javax.swing.UIManager.initialize(UIManager.java:1459)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
	at javax.swing.UIManager.getDefaults(UIManager.java:659)
	at javax.swing.UIManager.getColor(UIManager.java:701)
	at org.jfree.chart.JFreeChart.<clinit>(JFreeChart.java:143)
	at org.jfree.chart.ChartFactory.createXYLineChart(ChartFactory.java:1645)
	at ubic.gemma.core.analysis.preprocess.batcheffects.ComBat.writePlot(ComBat.java:355)
	at ubic.gemma.core.analysis.preprocess.batcheffects.ComBat.plot(ComBat.java:163)
	at ubic.gemma.core.analysis.preprocess.batcheffects.ExpressionExperimentBatchCorrectionServiceImpl.doComBat(ExpressionExperimentBatchCorrectionServiceImpl.java:227)
	at ubic.gemma.core.analysis.preprocess.batcheffects.ExpressionExperimentBatchCorrectionServiceImpl.comBat(ExpressionExperimentBatchCorrectionServiceImpl.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy200.comBat(Unknown Source)
	at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.getCorrectedData(PreprocessorServiceImpl.java:363)
	at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.batchCorrect(PreprocessorServiceImpl.java:184)
	at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.processExceptForVectorCreate(PreprocessorServiceImpl.java:246)
	at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.process(PreprocessorServiceImpl.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy205.process(Unknown Source)
	at ubic.gemma.core.loader.expression.DataUpdater.postprocess(DataUpdater.java:1163)
	at ubic.gemma.core.loader.expression.DataUpdater.replaceData(DataUpdater.java:667)
	at ubic.gemma.core.loader.expression.DataUpdater.addCountData(DataUpdater.java:240)
	at ubic.gemma.core.loader.expression.DataUpdater$$FastClassBySpringCGLIB$$389cfc7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
	at ubic.gemma.core.loader.expression.DataUpdater$$EnhancerBySpringCGLIB$$cd8c8942.addCountData(<generated>)
	at ubic.gemma.core.apps.RNASeqDataAddCli.doWork(RNASeqDataAddCli.java:195)
	at ubic.gemma.core.util.AbstractCLI.executeCommand(AbstractCLI.java:132)
	at ubic.gemma.core.apps.GemmaCLI.main(GemmaCLI.java:114)

**Comment by arteymix** [comment]
I actually opened this on Sanja's computer while reviewing some of the logs from the rnaseq pipeline. She uses X11 forwarding which results in $DISPLAY bring defined. I think this is the reason why sometimes plots are not generated.

I'll find a way to disable Swing/AWT rendering with JFreeChart.

**Comment by arteymix** [comment]
This is caused by JFreeChart statically initializing Swing's UIManager to get a default background color. It's completely unnecessary since we define ourselves the default background color.

This could be patched in JFreeChart or maybe via some workaround to prevent that static initialization. Maybe overriding the default AWT backend?

**Comment by arteymix** [comment]
It's kind of unfortunate because the rest of the API is decoupled from Swing and that silly property pulls the whole window toolkit.

**Comment by arteymix** [comment]
A workaround could be to unset $DISPLAY in the  gemma-cli wrapper.

**Comment by arteymix** [comment]
A better option is to add the -Djava.awt.headless=true JVM option.

https://stackoverflow.com/questions/10165761/java-cant-connect-to-x11-window-server-using-localhost10-0-as-the-value-of-t

**Comment by arteymix** [comment]
Ok, I've also set it on the server.
