### ISSUE TITLE
AssertionFailure: possible nonthreadsafe access to session in coexpression service

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#536]
This is generally caused by multiple threads sharing the same Hibernate session. The fix is to have each thread use a fresh session instead of sharing the current one.

```
[Gemma - http-nio-8181-exec-171 (2023-01-09 10:05:31,617)] ERROR ubic.gemma.persistence.retry.RetryLogger.close(50) | Retry failed after 2 attempts.
AssertionFailure: possible nonthreadsafe access to session
org.hibernate.AssertionFailure: possible nonthreadsafe access to session
    at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:112)
    at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:395)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:387)
    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:310)
    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349)
    at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:67)
    at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1166)
    at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1223)
    at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
    at ubic.gemma.persistence.service.analysis.expression.pca.PrincipalComponentAnalysisDaoImpl.findByExperiment(PrincipalComponentAnalysisDaoImpl.java:46)
    at sun.reflect.GeneratedMethodAccessor1025.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:155)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy150.findByExperiment(Unknown Source)
    at ubic.gemma.persistence.service.analysis.expression.pca.PrincipalComponentAnalysisServiceImpl.loadForExperiment(PrincipalComponentAnalysisServiceImpl.java:132)
    at sun.reflect.GeneratedMethodAccessor1024.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
    at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy151.loadForExperiment(Unknown Source)
    at ubic.gemma.core.analysis.preprocess.svd.SVDServiceHelperImpl.svdFactorAnalysis(SVDServiceHelperImpl.java:339)
    at ubic.gemma.core.analysis.preprocess.svd.SVDServiceHelperImpl.getImportantFactors(SVDServiceHelperImpl.java:272)
    at sun.reflect.GeneratedMethodAccessor2142.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy161.getImportantFactors(Unknown Source)
    at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.getImportantFactors(SampleCoexpressionAnalysisServiceImpl.java:317)
    at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.regressMajorFactors(SampleCoexpressionAnalysisServiceImpl.java:305)
    at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.loadDataMatrix(SampleCoexpressionAnalysisServiceImpl.java:278)
    at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.getMatrix(SampleCoexpressionAnalysisServiceImpl.java:232)
    at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.compute(SampleCoexpressionAnalysisServiceImpl.java:160)
    at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.load(SampleCoexpressionAnalysisServiceImpl.java:128)
    at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.loadTryRegressedThenFull(SampleCoexpressionAnalysisServiceImpl.java:106)
    at sun.reflect.GeneratedMethodAccessor1098.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
    at org.springframework.retry.suppor…
```

**Comment by ppavlidis** [comment]
Still applies in 2.0-alpha; needs focused follow-up. Audited during 2.0-alpha bug triage. `PrincipalComponentAnalysisDaoImpl.findByExperiment` (and other coexpression-service methods, see #728) still share the request session across worker threads. Each worker needs to open its own `SessionFactory.openSession()`.

**Comment by ppavlidis** [comment]
Closing as fixed by Phase 2 / Phase 3 refactors.

Verified on `phase2-acl-migrate` (worktree branch `agent-hibernate-session-threading` at SHA `78b9558343`):

- `PrincipalComponentAnalysisDaoImpl.findByExperiment` (and all sibling methods) use `sessionFactory.getCurrentSession()` — the standard Spring thread-bound session pattern. No fields hold a captured `Session`. (commits `8794176ef7` perf join-fetch, `c8356e09aa` PCA-reload cleanup, etc.)
- The originating caller in the stack trace, `SVDServiceHelperImpl`, no longer exists. It was refactored into `SVDServiceImpl` (gemma-core/src/main/java/ubic/gemma/core/analysis/preprocess/svd/SVDServiceImpl.java). `SVDServiceImpl` is entirely single-threaded — no `Executor`/`parallelStream`/`CompletableFuture`/`Thread` anywhere in it — and every public method is `@Transactional`, so each invocation gets its own thread-bound session via Spring.
- A broader grep over `gemma-core/src/main/java/ubic/gemma/core/analysis/preprocess/svd/` and `.../analysis/expression/pca/` for any threading primitive returns zero hits.

The class shape that produced the `AssertionFailure: possible nonthreadsafe access to session` stack is gone.

**Comment by ppavlidis** [comment]
Gemma 2 disposition: Fixed
