### ISSUE TITLE
ProcessedDataVectorCreate can yield db locking exceptions

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#631]
Example: GSE111384.

Running `makeProcessedData` on this works up until persisting vectors after batch correction, when we get the below (including a bit of extra context of logs).

This happens for many datasets, possibly all (have to look at my logs)

By the way, the Retry happens like 10 times. That seems a bit excessive.

```
2023-04-08 11:49:00,782 INFO 51193 [main] ubic.gemma.core.datastructure.matrix.ExpressionDataMatrixColumnSort.getBaselineLevels(128) | Baseline chosen: FactorValue 159573: treatment:reference substance role
2023-04-08 11:49:00,782 INFO 51193 [main] ubic.gemma.core.datastructure.matrix.ExpressionDataMatrixColumnSort.getBaselineLevels(163) | Falling back on choosing baseline arbitrarily: FactorValue 159575: batch:Batch_01_6/21/11
2023-04-08 11:49:01,981 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.batcheffects.ComBat.run(267) | Done
2023-04-08 11:49:01,990 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.batcheffects.ComBat.plot(157) | /tmp/14840.GSE111384.gammahat.histogram.2304290581303517853.png
2023-04-08 11:49:02,044 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.batcheffects.ComBat.plot(182) | /tmp/14840.GSE111384.deltahat.histogram.1366602789196869525.png
2023-04-08 11:50:23,976 INFO 51193 [main] ubic.gemma.persistence.service.expression.bioAssayData.DesignElementDataVectorDaoImpl.thawRawAndProcessed(162) | Thaw phase 4 30423 vector-associated probes thawed in 77ms
2023-04-08 11:50:23,979 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.ProcessedExpressionDataVectorCreateHelperServiceImpl.loadIntensities(355) | Computing intensities directly from processed data
2023-04-08 11:50:24,112 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.ProcessedExpressionDataVectorCreateHelperServiceImpl.updateRanks(270) | Load intensities: 134ms
2023-04-08 11:50:24,166 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.ProcessedExpressionDataVectorCreateHelperServiceImpl.updateRanks(280) | Updating ranks data for 30423 vectors ...
2023-04-08 11:50:24,175 WARN 51193 [main] ubic.gemma.persistence.service.AbstractDao.warnIfBatchingIsNotAdvisable(369) | Batching is not advisable with current flush mode COMMIT, will proceed with update on 30423 entities without invoking Session.flush() and Session.clear().
2023-04-08 11:50:24,210 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.ProcessedExpressionDataVectorCreateHelperServiceImpl.updateRanks(282) | Done
2023-04-08 11:50:32,660 ERROR 51193 [main] org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(127) | HHH000315: Exception executing batch [Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1]
2023-04-08 11:50:34,567 INFO 51193 [main] ubic.gemma.persistence.service.expression.bioAssayData.DesignElementDataVectorDaoImpl.thawRawAndProcessed(162) | Thaw phase 4 30423 vector-associated probes thawed in 77ms
2023-04-08 11:50:34,568 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.ProcessedExpressionDataVectorCreateHelperServiceImpl.loadIntensities(355) | Computing intensities directly from processed data
2023-04-08 11:50:34,706 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.ProcessedExpressionDataVectorCreateHelperServiceImpl.updateRanks(270) | Load intensities: 138ms
2023-04-08 11:50:34,819 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.ProcessedExpressionDataVectorCreateHelperServiceImpl.updateRanks(280) | Updating ranks data for 30423 vectors ...
2023-04-08 11:50:34,828 WARN 51193 [main] ubic.gemma.persistence.service.AbstractDao.warnIfBatchingIsNotAdvisable(369) | Batching is not advisable with current flush mode COMMIT, will proceed with update on 30423 entities without invoking Session.flush() and Session.clear().
2023-04-08 11:50:34,844 INFO 51193 [main] ubic.gemma.core.analysis.preprocess.ProcessedExpressionDataVectorCreateHelperServiceImpl.updateRanks(282) | Done
2023-04-08 11:50:35,050 ERROR 51193 [main] org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(127) | **HHH000315: Exception executing batch [Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1]
2023-04-08 11:50:35,067 WARN 51193 [main] ubic.gemma.persistence.retry.RetryLogger.onError(59) | Retry attempt #1 failed.
org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1**
        at org.hibernate.jdbc.Expectations$BasicExpectation.checkBatched(Expectations.java:81) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.jdbc.Expectations$BasicExpectation.verifyOutcome(Expectations.java:73) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.checkRowCounts(BatchingBatch.java:141) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:118) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.addToBatch(BatchingBatch.java:87) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3236) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3138) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3468) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:140) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:395) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:387) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:304) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:349) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1195) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:404) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:556) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:270) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at ubic.gemma.persistence.service.expression.bioAssayData.$Proxy139.createProcessedDataVectors(Unknown Source) ~[?:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.batchCorrect(PreprocessorServiceImpl.java:124) ~[gemma-core-1.29.9.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.process(PreprocessorServiceImpl.java:91) ~[gemma-core-1.29.9.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorService.process(PreprocessorService.java:64) ~[gemma-core-1.29.9.jar:?]
        at sun.reflect.GeneratedMethodAccessor730.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy177.process(Unknown Source) ~[?:?]
        at ubic.gemma.core.apps.ProcessedDataComputeCLI.processExperiment(ProcessedDataComputeCLI.java:133) ~[gemma-cli-1.29.9.jar:?]

```

**Comment by ppavlidis** [comment]
https://github.com/PavlidisLab/GemmaCuration/issues/302 notes another case (GSE130098 ) but I have dozens more.

**Comment by ppavlidis** [comment]
The following are the current experiments that exposed this problem (including ones mentioned above). `makeProcessedData` will have to be run on them when it is fixed (there may be more)

```
GSE130098
GSE10421    
GSE24818    
GSE17260    
GSE26378    
GSE16065    
GSE32063    
GSE9982     
GSE32507    
GSE9174     
GSE29609    
GSE44263    
GSE49473    
GSE33833    
GSE38325    
GSE51942    
GSE11179    
GSE111384   
GSE37569    
GSE4913     
GSE9945     
GSE31718    
GSE40047    
GSE40234    
GSE26415    
GSE14529    
GSE9806     
GSE17901    
GSE15739    
GSE21315    
GSE54083    
GSE44000    
GSE87188    
GSE72621    
GSE21335    
```

**Comment by arteymix** [comment]
That line:

> 2023-04-08 11:50:34,828 WARN 51193 [main] ubic.gemma.persistence.service.AbstractDao.warnIfBatchingIsNotAdvisable(369) | Batching is not advisable with current flush mode COMMIT, will proceed with update on 30423 entities without invoking Session.flush() and Session.clear().

AbstractDao only flush/clear if the current flush mode is set to AUTO or MANUAL. There's a bug in gsec that switches the flush mode to COMMIT in the update advice #494. This means SQL statements are sent only when the transaction is committed, and I guess there are discrepancies between the session state and the database. We could attempt switching it back to AUTO for this method or maybe make sure that the there is no stale data when we start the updating ranks by refreshing the entity.

**Comment by arteymix** [comment]
Oh, also the advice applies because the method is named `updateRanks`. We could simply rename it or remove the ``@Secured` annotation.
