### ISSUE TITLE
handling of factors when unassigned to samples needs review

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#632]
In ExpressionDataMatrixColumnSort.getBaselineLevels we have the block below (~line 135+) to handle the case when we need to choose a factorvalue as baseline arbitrarily.

A common case of this is for batch factors, which always have an arbitrary choice of baseline (this is only used during batch correction).

However, there are experiments like [GSE192399](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=23360) that have a batch factor but it is not assigned to any samples (why this is the case is another issue). 

This leads to the sort of error shown at the bottom, which is confusing.

Note that `samplesUsed` is the samples considered for batch correction.  I'm committing a change to help address this confusing error message.

```
             if ( !result.containsKey( factor ) ) { // fallback
                    FactorValue arbitraryBaselineFV = null;

                    if ( samplesUsed != null ) {
                        // make sure we choose a fv that is actually used (see above for non-arbitrary case)
                        for ( FactorValue fv : factor.getFactorValues() ) {
                            for ( BioMaterial bm : samplesUsed ) {
                                for ( FactorValue bfv : bm.getFactorValues() ) {
                                    if ( fv.equals( bfv ) ) {
                                        arbitraryBaselineFV = fv;
                                        break;
                                    }
                                }
                                if ( arbitraryBaselineFV != null )
                                    break;
                            }
                            if ( arbitraryBaselineFV != null )
                                break;
                        }

                    } else {
                        //---> it doesn't make sense to do this, but confusing why it would be null in the next block.
                        arbitraryBaselineFV = factor.getFactorValues().iterator().next();
                    }

                    if ( arbitraryBaselineFV == null ) {
                        throw new IllegalStateException(
                                "No baseline could be identified for factor:  " + factor + " has " + factor
                                        .getFactorValues().size() + " factor values" );
                    }
                    ExpressionDataMatrixColumnSort.log
                            .info( "Falling back on choosing baseline arbitrarily: " + arbitraryBaselineFV );
                    result.put( factor, arbitraryBaselineFV );
                }
```

```
2023-04-08 11:47:08,842 ERROR 51193 [main] ubic.gemma.core.util.AbstractCLI.addErrorObject(432) | No baseline could be identified for factor:  ExperimentalFactor Id=38050 Name=batch has 3 factor values
java.lang.IllegalStateException: No baseline could be identified for factor:  ExperimentalFactor Id=38050 Name=batch has 3 factor values
        at ubic.gemma.core.datastructure.matrix.ExpressionDataMatrixColumnSort.getBaselineLevels(ExpressionDataMatrixColumnSort.java:160) ~[gemma-core-1.29.9.jar:?]
        at ubic.gemma.core.analysis.util.ExperimentalDesignUtils.getBaselineConditions(ExperimentalDesignUtils.java:130) ~[gemma-core-1.29.9.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ExpressionExperimentBatchCorrectionServiceImpl.getDesign(ExpressionExperimentBatchCorrectionServiceImpl.java:276) ~[gemma-core-1.29.9.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ExpressionExperimentBatchCorrectionServiceImpl.comBat(ExpressionExperimentBatchCorrectionServiceImpl.java:142) ~[gemma-core-1.29.9.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.getCorrectedData(PreprocessorServiceImpl.java:265) ~[gemma-core-1.29.9.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.batchCorrect(PreprocessorServiceImpl.java:120) ~[gemma-core-1.29.9.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.process(PreprocessorServiceImpl.java:91) ~[gemma-core-1.29.9.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorService.process(PreprocessorService.java:64) ~[gemma-core-1.29.9.jar:?]
        at sun.reflect.GeneratedMethodAccessor730.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy177.process(Unknown Source) ~[?:?]
        at ubic.gemma.core.apps.ProcessedDataComputeCLI.processExperiment(ProcessedDataComputeCLI.java:133) ~[gemma-cli-1.29.9.jar:?]
        at ubic.gemma.core.apps.ProcessedDataComputeCLI.doWork(ProcessedDataComputeCLI.java:102) ~[gemma-cli-1.29.9.jar:?]
        at ubic.gemma.core.util.AbstractCLI.executeCommand(AbstractCLI.java:143) ~[gemma-cli-1.29.9.jar:?]
        at ubic.gemma.core.apps.GemmaCLI.main(GemmaCLI.java:141) ~[gemma-cli-1.29.9.jar:?]
```

**Comment by ppavlidis** [comment]
The fundamental problem is the lack of assignment, the error message should now be clearer.
