### ISSUE TITLE
SampleCoexpressionAnalysisService can't cope with DEInclude (missing factorvalues)

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#664]
example [GSE37250](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=7115&tab=admin) 

Probably we need to just ignore factors that have missing value like this, but that means an inequivalence in how we do the sample-coexpression matrix as we like to regress out known factors.

This could reflect a curation issue (maybe the experiment should be split, not subset), but handling this gracefully would be better.

```
2023-04-21 23:43:18,121 INFO 35088 [main] ubic.gemma.core.datastructure.matrix.ExpressionDataMatrixColumnSort.getBaselineLevels(128) | Baseline chosen: FactorValue 99509: disease:reference subject role
2023-04-21 23:43:18,122 INFO 35088 [main] ubic.gemma.core.datastructure.matrix.ExpressionDataMatrixColumnSort.getBaselineLevels(169) | Falling back on choosing baseline arbitrarily: FactorValue 128173: collection of material:DE_Include
2023-04-21 23:43:18,161 ERROR 35088 [main] ubic.gemma.core.util.AbstractCLI.addErrorObject(432) | Missing values not tolerated in design matrix
java.lang.IllegalStateException: Missing values not tolerated in design matrix
        at ubic.gemma.core.analysis.util.ExperimentalDesignUtils.buildDesignMatrix(ExperimentalDesignUtils.java:99) ~[gemma-core-1.29.10.jar:?]
        at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.regressionResiduals(SampleCoexpressionAnalysisServiceImpl.java:365) ~[gemma-core-1.29.10.jar:?]
        at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.regressMajorFactors(SampleCoexpressionAnalysisServiceImpl.java:309) ~[gemma-core-1.29.10.jar:?]
        at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.loadDataMatrix(SampleCoexpressionAnalysisServiceImpl.java:277) ~[gemma-core-1.29.10.jar:?]
        at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.getMatrix(SampleCoexpressionAnalysisServiceImpl.java:231) ~[gemma-core-1.29.10.jar:?]
        at ubic.gemma.persistence.service.analysis.expression.sampleCoexpression.SampleCoexpressionAnalysisServiceImpl.compute(SampleCoexpressionAnalysisServiceImpl.java:159) ~[gemma-core-1.29.10.jar:?]
        at sun.reflect.GeneratedMethodAccessor720.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy148.compute(Unknown Source) ~[?:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.processForSampleCorrelation(PreprocessorServiceImpl.java:238) ~[gemma-core-1.29.10.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.processDiagnostics(PreprocessorServiceImpl.java:134) ~[gemma-core-1.29.10.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.process(PreprocessorServiceImpl.java:94) ~[gemma-core-1.29.10.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorService.process(PreprocessorService.java:64) ~[gemma-core-1.29.10.jar:?]
        at sun.reflect.GeneratedMethodAccessor705.invoke(Unknown Source) ~[?:?]

```

**Comment by ppavlidis** [comment]
I implemented a simple fix in 4fd809f5b89d66b5f48f888cee17388ad741c399

But it's not all that pleasant.
