### ISSUE TITLE
Batch correction can fail when there is a DEExclude/Include factor

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#678]
The problem is when a factor that is valid for the DEInclude part of the experiment is not populated for the rest of the samples. This is "normal" - example: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE27183 but causes issues for ComBat.

In batch correction, we control for the other aspects of the experimental design. In general, not having factorvlaues assigned to all samples is a problem, but in a DEInclude/Exclude it can be appropriate. 

However, because some FVs are null, making the design matrix for batch correction fails.

Batch correction should:

* not use DE_Exclude/Include as a factor (I thought it did but haven't found it in the code)
* be tolerant of missing FVs when there is a DE_Exclude/Include factor. We can use a random dummy value in the factor just for the purposes of building a valid design matrix for batch correction
* not tolerate missing FVs in other situations as this indicates curation is not complete

> 2023-05-08 15:38:08,594 ^[[1;31mERROR^[[m ^[[35m48560^[[m [main] ^[[36mubic.gemma.core.util.AbstractCLI.addErrorObject(432)^[[m | null
java.lang.NullPointerException: null
        at ubic.basecode.math.linearmodels.DesignMatrix.buildDesign(DesignMatrix.java:572) ~[baseCode-1.1.16.jar:?]
        at ubic.basecode.math.linearmodels.DesignMatrix.designMatrix(DesignMatrix.java:687) ~[baseCode-1.1.16.jar:?]
        at ubic.basecode.math.linearmodels.DesignMatrix.add(DesignMatrix.java:167) ~[baseCode-1.1.16.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ComBat.computeDesignMatrix(ComBat.java:530) ~[gemma-core-1.29.11.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ComBat.<init>(ComBat.java:119) ~[gemma-core-1.29.11.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ExpressionExperimentBatchCorrectionServiceImpl.doComBat(ExpressionExperimentBatchCorrectionServiceImpl.java:231) ~[gemma-core-1.29.11.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ExpressionExperimentBatchCorrectionServiceImpl.comBat(ExpressionExperimentBatchCorrectionServiceImpl.java:144) ~[gemma-core-1.29.11.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.getCorrectedData(PreprocessorServiceImpl.java:269) ~[gemma-core-1.29.11.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.batchCorrect(PreprocessorServiceImpl.java:120) ~[gemma-core-1.29.11.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorServiceImpl.process(PreprocessorServiceImpl.java:91) ~[gemma-core-1.29.11.jar:?]
        at ubic.gemma.core.analysis.preprocess.PreprocessorService.process(PreprocessorService.java:64) ~[gemma-core-1.29.11.jar:?]

**Comment by ppavlidis** [comment]
Also affects GSE40990

**Comment by ppavlidis** [comment]
An alternative solution, which is much simpler if a bit inelegant, is to supply a dummy factor value in the experimental design just to satisfy the requirements for batch correction, rather than trying to address this programmatically (which requires detecting DEExclude etc.)

Additionally, when this situation arises, it may suggest a split of the experiment is appropriate.

**Comment by ppavlidis** [comment]
http://gemma.msl.ubc.ca/ont/TGEMO_00122 is our existing term for "unspecified factor value"

On this basis I am closing this issue, it's best handled by curation.

**Comment by ppavlidis** [comment]
It turns out there are about 400 such experiments so it will actually be easier to deal with this in code, though the curation approach should still happen as we encounter these studies.
