### ISSUE TITLE
Deleting a DEA task fail from the GUI

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#744]
https://github.com/PavlidisLab/GemmaCuration/issues/350

**Comment by arteymix** [comment]
```
java.lang.IllegalArgumentException: ParentIdentity cannot be null
        at org.springframework.util.Assert.notNull(Assert.java:112) ~[spring-core-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at gemma.gsec.acl.domain.AclDaoImpl.findChildren(AclDaoImpl.java:160) ~[gemma-gsec-0.0.12.jar:?]
        at gemma.gsec.acl.domain.AclDaoImpl.delete(AclDaoImpl.java:74) ~[gemma-gsec-0.0.12.jar:?]
        at gemma.gsec.acl.domain.AclServiceImpl.deleteAcl(AclServiceImpl.java:80) ~[gemma-gsec-0.0.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy3776.deleteAcl(Unknown Source) ~[?:?]
        at gemma.gsec.acl.BaseAclAdvice.deleteAcl(BaseAclAdvice.java:521) ~[gemma-gsec-0.0.12.jar:?]
        at gemma.gsec.acl.BaseAclAdvice.process(BaseAclAdvice.java:712) ~[gemma-gsec-0.0.12.jar:?]
```

**Comment by arteymix** [comment]
Fixed by https://github.com/PavlidisLab/gsec/commit/c40565e26a01bed17df12a7dc603469cf9fa5cf7. I'll be testing it out. I'm also adding `@Nullable` annotations to gsec to prevent other such bugs.
