### ISSUE TITLE
File is missing on ArrayExpress FTP server

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#766]
> java.lang.RuntimeException: Cancelled, or couldn't fetch pub/databases/microarray/data/experiment/SMDB/E-SMDB-1853/E-SMDB-1853.sdrf.txt, make sure the file exists on the remote server and permissions are granted.
	at ubic.gemma.core.loader.expression.arrayExpress.SDRFFetcherTest.testFetch(SDRFFetcherTest.java:41)
Caused by: java.io.FileNotFoundException: Didn't get expected file information for pub/databases/microarray/data/experiment/SMDB/E-SMDB-1853/E-SMDB-1853.sdrf.txt (3 attempts)
	at ubic.gemma.core.loader.expression.arrayExpress.SDRFFetcherTest.testFetch(SDRFFetcherTest.java:41)

**Comment by ppavlidis** [comment]
This test is a relic as we aren't directly loading ArrayExpress data that way anyway (any longer)

**Comment by arteymix** [comment]
We're ignoring it for now. I will schedule its removal in the 1.31.

**Comment by ppavlidis** [comment]
Fix landed in commit `36eea2ccbe` on branch `agent-bug-audit-b-2026-05-25` (will merge into `phase2-acl-migrate`). The disabled `SDRFFetcherTest` has been removed; the SDRFFetcher class itself is left in place but is unused outside that test, so a follow-up could prune it entirely. Closing as resolved.

**Comment by ppavlidis** [comment]
Gemma 2 disposition: Fixed

**Comment by ppavlidis** [comment]
Fix landed in https://github.com/PavlidisLab/Gemma/commit/36eea2ccbe
