### ISSUE TITLE
characteristic browser is broken

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#773]
https://gemma.msl.ubc.ca/characteristicBrowser.html

Searches result in an exception.

Logs have this, not confident it is relevant

```
[Gemma - http-nio-8181-exec-644 (2023-07-17 15:21:07,655)] WARN org.directwebremoting.util.CommonsLoggingOutput.warn(67) | Method execution failed:
java.lang.StackOverflowError: null
        at ubic.gemma.web.util.AnchorTagUtil.getExperimentalDesignLink(AnchorTagUtil.java:41) ~[classes/:?]
        at ubic.gemma.web.util.AnchorTagUtil.getExperimentalDesignLink(AnchorTagUtil.java:41) ~[classes/:?]
        at ubic.gemma.web.util.AnchorTagUtil.getExperimentalDesignLink(AnchorTagUtil.java:41) ~[classes/:?]
        at ubic.gemma.web.util.AnchorTagUtil.getExperimentalDesignLink(AnchorTagUtil.java:41) ~[classes/:?]
        at ubic.gemma.web.util.AnchorTagUtil.getExperimentalDesignLink(AnchorTagUtil.java:41) ~[classes/:?]
        at ubic.gemma.web.util.AnchorTagUtil.getExperimentalDesignLink(AnchorTagUtil.java:41) ~[classes/:?]
        at ubic.gemma.web.util.AnchorTagUtil.getExperimentalDesignLink(AnchorTagUtil.java:41) ~[classes/:?]
```

**Comment by arteymix** [comment]
It's ready for testing now on the development server!

**Comment by ppavlidis** [comment]
It's working but I ran into a problem again. It seems if your search yields no results, it bombs with:
<img width="567" alt="image" src="https://github.com/PavlidisLab/Gemma/assets/206415/cbfad67b-0aa7-4227-8ef2-24e767a108ed">

For example try to search with 'fdadfihuah'.

**Comment by ppavlidis** [comment]
Another odd behavior: if you change just the **Category** for an annotation and "save", it looks like it doesn't work. But if you do it a second time, it shows up.

I suspect something isn't getting refreshed. 

I've also noticed this behaviour in the Experiment Tagger.
