### ISSUE TITLE
ExpressionExperimentService.loadAllValueObjectsTaxon() fails (works fine previously).

### ISSUE THREAD

**Issue by nzllim** [PavlidisLab/Gemma#81]
As title. I suspect a malformed HQL statement.

Stacktrace:

[Gemma 2019-06-09 14:44:58,890] ERROR [main] org.hibernate.hql.ast.ErrorCounter.reportError(56) |  Invalid path: 'taxon.id'
[Gemma 2019-06-09 14:44:58,984] ERROR [main] org.hibernate.hql.ast.ErrorCounter.reportError(56) | <AST>:0:0: unexpected end of subtree
[Gemma 2019-06-09 14:44:58,985] ERROR [main] org.hibernate.hql.ast.ErrorCounter.reportError(56) |  left-hand operand of a binary operator was null
Traceback (most recent call last):
	at org.hibernate.hql.ast.QuerySyntaxException.convert(QuerySyntaxException.java:54)
	at org.hibernate.hql.ast.QuerySyntaxException.convert(QuerySyntaxException.java:47)
	at org.hibernate.hql.ast.ErrorCounter.throwQueryException(ErrorCounter.java:82)
	at org.hibernate.hql.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:261)
	at org.hibernate.hql.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:185)
	at org.hibernate.hql.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:136)
	at org.hibernate.engine.query.HQLQueryPlan.<init>(HQLQueryPlan.java:101)
	at org.hibernate.engine.query.HQLQueryPlan.<init>(HQLQueryPlan.java:80)
	at org.hibernate.engine.query.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:124)
	at org.hibernate.impl.AbstractSessionImpl.getHQLQueryPlan(AbstractSessionImpl.java:156)
	at org.hibernate.impl.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:135)
	at org.hibernate.impl.SessionImpl.createQuery(SessionImpl.java:1770)
	at ubic.gemma.persistence.service.expression.experiment.ExpressionExperimentDaoImpl.postProcessVoQuery(ExpressionExperimentDaoImpl.java:1730)
	at ubic.gemma.persistence.service.expression.experiment.ExpressionExperimentDaoImpl.getLoadValueObjectsQueryString(ExpressionExperimentDaoImpl.java:1553)
	at ubic.gemma.persistence.service.expression.experiment.ExpressionExperimentDaoImpl.loadValueObjectsPreFilter(ExpressionExperimentDaoImpl.java:1228)
	at ubic.gemma.persistence.service.expression.experiment.ExpressionExperimentDaoImpl.loadValueObjectsPreFilter(ExpressionExperimentDaoImpl.java:1668)
	at ubic.gemma.persistence.service.expression.experiment.ExpressionExperimentDaoImpl.loadAllValueObjectsTaxon(ExpressionExperimentDaoImpl.java:1049)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy50.loadAllValueObjectsTaxon(Unknown Source)
	at ubic.gemma.persistence.service.expression.experiment.ExpressionExperimentServiceImpl.loadAllValueObjectsTaxon(ExpressionExperimentServiceImpl.java:765)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy59.loadAllValueObjectsTaxon(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
org.hibernate.hql.ast.QuerySyntaxException: org.hibernate.hql.ast.QuerySyntaxException: Invalid path: 'taxon.id' [select ee.id as id, ee.name, ee.source, ee.shortName, ee.metadata, ee.numberOfDataVectors, acc.accession, ED.name, ED.webUri, ee.description, ee.taxon.commonName, ee.taxon.id, s.lastUpdated, s.troubled, s.needsAttention, s.curationNote, ee.numberOfSamples, EDES.id,  aoi, sid , ee.batchEffect, ee.batchConfound, eNote, eAttn, eTrbl, geeq from ubic.gemma.model.expression.experiment.ExpressionExperiment as ee left join ee.accession acc  left join acc.externalDatabase as ED  join ee.experimentalDesign as EDES  join ee.curationDetails as s  left join s.lastNeedsAttentionEvent as eAttn  left join ee.geeq as geeq left join s.lastNoteUpdateEvent as eNote  left join s.lastTroubledEvent as eTrbl , gemma.gsec.acl.domain.AclObjectIdentity as aoi inner join aoi.ownerSid sid where aoi.identifier = ee.id and aoi.type = 'ubic.gemma.model.expression.experiment.ExpressionExperiment'and ( taxon.id =:taxonid  ) order by ee.id ]

**Comment by ppavlidis** [comment]
I believe this is already fixed in the upcoming release
