### ISSUE TITLE
HibernateSystemException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.DifferentialExpressionAnalysis.resultSets, could not initialize proxy - no Session; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.DifferentialExpressionAnalysis.resultSets, could not initialize proxy - no Session

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#838]
```
HibernateSystemException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.DifferentialExpressionAnalysis.resultSets, could not initialize proxy - no Session; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.DifferentialExpressionAnalysis.resultSets, could not initialize proxy - no Session
org.springframework.orm.hibernate4.HibernateSystemException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.DifferentialExpressionAnalysis.resultSets, could not initialize proxy - no Session; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.DifferentialExpressionAnalysis.resultSets, could not initialize proxy - no Session
    at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:185)
    at org.springframework.orm.hibernate4.HibernateExceptionTranslator.convertHibernateAccessException(HibernateExceptionTranslator.java:56)
    at org.springframework.orm.hibernate4.HibernateExceptionTranslator.translateExceptionIfPossible(HibernateExceptionTranslator.java:43)
    at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:58)
    at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:163)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
    at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:51)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy100.remove(Unknown Source)
    at ubic.gemma.persistence.service.AbstractService.remove(AbstractService.java:131)
    at ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionAnalysisServiceImpl.remove(DifferentialExpressionAnalysisServiceImpl.java:230)
    at ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionAnalysisServiceImpl.remove(DifferentialExpressionAnalysisServiceImpl.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
    at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy103.remove(Unknown Source)
    at ubic.gemma.core.tasks.analysis.diffex.DifferentialExpressionAnalysisTaskImpl.call(DifferentialExpressionAnalysisTaskImpl.java:72)
    at ubic.gemma.core.tasks.analysis.diffex.DifferentialExpressionAnalysisTaskImpl.call(DifferentialExpressionAnalysisTaskImpl.java:43)
    at ubic.gemma.core.job.executor.common.ExecutingTask.call(ExecutingTask.java:52)
    at ubic.gemma.core.job.executor.common.ExecutingTask.call(ExecutingTask.java:27)
    at org.springframework.security.concurrent.DelegatingSecurityContextCallable.call(DelegatingSecurityContextCallable.java:83)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)
Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.DifferentialExpressionAnalysis.resultSets, could not initialize proxy - no Session
    at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:569)
    at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:188)
    at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:548)
    at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:126)
    at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:180)
    at ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionAnalysisDaoImpl.lambda$remove$3(DifferentialExpressionAnalysisDaoImpl.java:604)
    at org.hibernate.jdbc.WorkExecutor.executeWork(WorkExecutor.java:54)
    at org.hibernate.internal.SessionImpl$2.accept(SessionImpl.java:1943)
    at org.hibernate.internal.SessionImpl$2.accept(SessionImpl.java:1940)
    at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:293)
    at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:1961)
    at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:1947)
    at ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionAnalysisDaoImpl.remove(DifferentialExpressionAnalysisDaoImpl.java:599)
    at ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionAnalysisDaoImpl.remove(DifferentialExpressionAnalysisDaoImpl.java:56)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Nat…

**Comment by arteymix** [comment]
Fixed by 4eda59f23baa55950f54d20ff2a9d5c49bfca499
