### ISSUE TITLE
rnaseqBatchInfo raises a java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#85]
I have set `gemma.fastq.headers.dir=/cosmos/data/pipeline-output/rnaseq/fastq_headers` in `Gemma.properties` and launched the following command:

`/space/grp/bin/gemmaCli.sh rnaseqBatchInfo -u ********* -p ********* -e GSE97713`

The standard output:

```
Loading jars from /space/grp/lib/Gemma
[Gemma 2019-12-09 15:53:34,700] INFO [main] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(172) | Loading properties file from class path resource [default.properties]
[Gemma 2019-12-09 15:53:38,617] INFO [main] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(172) | Loading properties file from class path resource [default.properties]
[Gemma 2019-12-09 15:53:38,889] INFO [main] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(172) | Loading properties file from class path resource [default.properties]
[Gemma 2019-12-09 15:53:38,922] INFO [main] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(172) | Loading properties file from class path resource [default.properties]
[Gemma 2019-12-09 15:53:38,953] INFO [main] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(172) | Loading properties file from class path resource [default.properties]
[Gemma 2019-12-09 15:53:38,993] INFO [main] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(172) | Loading properties file from class path resource [default.properties]
[Gemma 2019-12-09 15:53:39,014] INFO [main] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(172) | Loading properties file from class path resource [default.properties]
[Gemma 2019-12-09 15:53:39,035] INFO [main] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(172) | Loading properties file from class path resource [default.properties]
[Gemma 2019-12-09 15:53:39,054] INFO [main] org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(172) | Loading properties file from class path resource [default.properties]
[Gemma 2019-12-09 15:53:42,028] INFO [fmaOntology_load_thread_pMA9i] ubic.basecode.ontology.OntologyLoader.loadMemoryModel(219) | Connecting to http://purl.obolibrary.org/obo/fma.owl
[Gemma 2019-12-09 15:53:42,483] INFO [main] ubic.gemma.persistence.util.SpringContextUtil.getApplicationContext(64) | Got context in 9368ms
[Gemma 2019-12-09 15:53:42,601] INFO [main] ubic.gemma.core.util.AbstractSpringAwareCLI.authenticate(226) | Logged in as poirigui
[Gemma 2019-12-09 15:53:42,778] INFO [main] ubic.gemma.core.apps.RNASeqBatchInfoCli.doWork(72) | Checking folders for existing experiments in /cosmos/data/pipeline-output/rnaseq/fastq_headers
```

The standard error:

```
Gemma version 1.25.16 built 20191118-1658
Gemma CLI error: java.lang.reflect.InvocationTargetException - null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ubic.gemma.core.apps.GemmaCLI.main(GemmaCLI.java:115)
Caused by: org.hibernate.LazyInitializationException: could not initialize proxy - no Session
        at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:167
Caused by: org.hibernate.LazyInitializationException: could not initialize proxy - no Session                                                                                                   [0/287]
        at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:167)
        at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:215)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:190)
        at ubic.gemma.model.common.description.DatabaseEntry_$$_javassist_123.getAccession(DatabaseEntry_$$_javassist_123.java)
        at ubic.gemma.core.analysis.preprocess.batcheffects.BatchInfoPopulationServiceImpl.needToRun(BatchInfoPopulationServiceImpl.java:251)
        at ubic.gemma.core.analysis.preprocess.batcheffects.BatchInfoPopulationServiceImpl.fillBatchInformation(BatchInfoPopulationServiceImpl.java:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy198.fillBatchInformation(Unknown Source)
        at ubic.gemma.core.apps.RNASeqBatchInfoCli.doWork(RNASeqBatchInfoCli.java:79)
        at ubic.gemma.core.apps.RNASeqBatchInfoCli.main(RNASeqBatchInfoCli.java:36)
        ... 5 more
```

**Comment by ppavlidis** [comment]
oops, this CLI is deprecated. You can just use the regular batch information too (fillBatchInfo).
