### ISSUE TITLE
Failed to lazily initialize a collection of role

### ISSUE THREAD

**Issue by Mahanrn** [PavlidisLab/Gemma#856]
Running `gemma-cli makeProcessedData -e GSE101149 -force` for [GSE101149](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE101149) returns:

`Errors occurred during the processing of 1 objects:
ExpressionExperiment Id=29496 Name=Microarray expression data from leukemia cell lines RS4;11 and REH with CASC15 KD or KO respectively Short Name=GSE101149:
        failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.ExpressionAnalysisResultSet.results, could not initialize proxy - no Session; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.ExpressionAnalysisResultSet.results, could not initialize proxy - no Session
`
This doesn't seem to be an issue specific to this dataset, hence I'm posting it here. Already told @arteymix about it.

Stack trace:
`Removing meta analyses with this experiment...
2023-09-18 10:03:51,082 ERROR 6148 [main] ubic.gemma.core.util.AbstractCLI.addErrorObject(399) | failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.ExpressionAna$
ysisResultSet.results, could not initialize proxy - no Session; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis$
expression.diff.ExpressionAnalysisResultSet.results, could not initialize proxy - no Session
org.springframework.orm.hibernate4.HibernateSystemException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.ExpressionAnalysisResultSet.results, could not in$
tialize proxy - no Session; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: ubic.gemma.model.analysis.expression.diff.ExpressionAnalysisR$
sultSet.results, could not initialize proxy - no Session
        at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:185) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.orm.hibernate4.HibernateExceptionTranslator.convertHibernateAccessException(HibernateExceptionTranslator.java:56) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.orm.hibernate4.HibernateExceptionTranslator.translateExceptionIfPossible(HibernateExceptionTranslator.java:43) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:58) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE$
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:163) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:51) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy88.remove(Unknown Source) ~[?:?]
        at ubic.gemma.persistence.service.AbstractService.remove(AbstractService.java:131) ~[gemma-core-1.30.1.jar:?]
        at ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionAnalysisServiceImpl.remove(DifferentialExpressionAnalysisServiceImpl.java:230) ~[gemma-core-1.30.1.jar:?]
        at ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionAnalysisServiceImpl.remove(DifferentialExpressionAnalysisServiceImpl.java:50) ~[gemma-core-1.30.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]`

**Comment by arteymix** [comment]
Fixed in cdfb649afe8277505ba39024d824f3b70b1e98b6
