### ISSUE TITLE
Could not execute batch; SQL

### ISSUE THREAD

**Issue by Mahanrn** [PavlidisLab/Gemma#857]
Similar to my previous post, I showed this to @arteymix. Seems like it's not specific to this dataset, so I'm posting it here. Running `gemma-cli makeProcessedData -e GSE138486 -force` for [GSE138486](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE138486) returns: 

`Errors occurred during the processing of 1 objects:
ExpressionExperiment Id=29352 Name=Expression data of human melanoma cells plus/minus Androgen Receptor (AR) silencing by two independent shRNAs Short Name=GSE138486:
        could not execute batch; SQL [insert into PROCESSED_EXPRESSION_DATA_VECTOR (BIO_ASSAY_DIMENSION_FK, DESIGN_ELEMENT_FK, DATA, QUANTITATION_TYPE_FK, RANK_BY_MEAN, RANK_BY_MAX, EXPRESSION_EXPERIMENT_FK, ID) values (?, ?, ?, ?, ?, ?, ?, ?)]; constraint [PRIMARY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
`

Stack Trace: 
`could not execute batch; SQL [insert into PROCESSED_EXPRESSION_DATA_VECTOR (BIO_ASSAY_DIMENSION_FK, DESIGN
_ELEMENT_FK, DATA, QUANTITATION_TYPE_FK, RANK_BY_MEAN, RANK_BY_MAX, EXPRESSION_EXPERIMENT_FK, ID) values (?, ?, ?, ?, ?, ?, ?, ?)]; constraint [PRIMARY]; nested exception is org.hibernate.exception.Const
raintViolationException: could not execute batch
org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into PROCESSED_EXPRESSION_DATA_VECTOR (BIO_ASSAY_DIMENSION_FK, DESIGN_ELEMENT_FK, DATA, QUANTITATION_TYPE_FK$
 RANK_BY_MEAN, RANK_BY_MAX, EXPRESSION_EXPERIMENT_FK, ID) values (?, ?, ?, ?, ?, ?, ?, ?)]; constraint [PRIMARY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not exec$
te batch
        at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:138) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.orm.hibernate4.HibernateExceptionTranslator.convertHibernateAccessException(HibernateExceptionTranslator.java:56) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.orm.hibernate4.HibernateExceptionTranslator.translateExceptionIfPossible(HibernateExceptionTranslator.java:43) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:58) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE$
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:163) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:51) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy81.save(Unknown Source) ~[?:?]
`

`Caused by: org.hibernate.exception.ConstraintViolationException: could not execute batch
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:122) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.addToBatch(BatchingBatch.java:87) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3079) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3521) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:88) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:395) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:387) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.spi.ActionQueue.executeInserts(ActionQueue.java:288) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:204) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:193) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:321) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:286) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:192) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:208) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:151) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:762) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:755) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.spi.CascadingAction$7.cascade(CascadingAction.java:315) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:396) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:339) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]`

Stack trace in this case is very long, I've only included some initial parts.

**Comment by arteymix** [comment]
Fixed in 87f9a0d574d0d59321b1e481b08bc7d4e7b69e5c
