### ISSUE TITLE
updating of generic platforms fails

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#878]
`$GEMMACMD genericPlatform  -t mouse`

```
Name=placenta expressed transcript 1 NCBI Gene ID=76509;Gene Id=681887 Name=Plet1os Official Symbol=Plet1os Official Name=placenta expressed transcript 1, opposite strand NCBI Gene ID=69631
2023-09-29 12:41:13,384 WARN 36859 [main] ubic.gemma.core.apps.GenericGenelistDesignGenerator.getExistingGeneMap(434) | More than one gene for: CompositeSequence Id=18597608 Name=Nt5dc2: Gene Id=782609 Name=Stab1 Official Symbol=Stab1 Official\
 Name=stabilin 1 NCBI Gene ID=192187;Gene Id=684822 Name=Nt5dc2 Official Symbol=Nt5dc2 Official Name=5'-nucleotidase domain containing 2 NCBI Gene ID=70021
2023-09-29 12:41:13,385 WARN 36859 [main] ubic.gemma.core.apps.GenericGenelistDesignGenerator.getExistingGeneMap(434) | More than one gene for: CompositeSequence Id=19824354 Name=Zfy1: Gene Id=593032 Name=Zfy1 Official Symbol=Zfy1 Official Nam\
e=zinc finger protein 1, Y-linked NCBI Gene ID=22767;Gene Id=593050 Name=Zfy2 Official Symbol=Zfy2 Official Name=zinc finger protein 2, Y-linked NCBI Gene ID=22768
2023-09-29 12:41:13,779 INFO 36859 [main] ubic.gemma.core.apps.GenericGenelistDesignGenerator.doWork(262) | No DB entry for BioSequence Id=14370174 Name=NM_015728(Gene Id=474664 Name=Slc33a1 Official Symbol=Slc33a1 Official Name=solute carrier\
 family 33 (acetyl-CoA transporter), member 1 NCBI Gene ID=11416), will look for a better sequence to use ...
2023-09-29 12:41:14,016 ERROR 36859 [main] ubic.gemma.core.util.AbstractCLI.executeCommand(136) | genericPlatform failed.
org.springframework.dao.InvalidDataAccessApiUsageException: detached entity passed to persist: ubic.gemma.model.common.description.DatabaseEntry; nested exception is org.hibernate.PersistentObjectException: detached entity passed to persist: u\
bic.gemma.model.common.description.DatabaseEntry
        at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:163) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.orm.hibernate4.HibernateExceptionTranslator.convertHibernateAccessException(HibernateExceptionTranslator.java:56) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.orm.hibernate4.HibernateExceptionTranslator.translateExceptionIfPossible(HibernateExceptionTranslator.java:43) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:58) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:163) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:51) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy104.create(Unknown Source) ~[?:?]
        at ubic.gemma.persistence.persister.GenomePersister.persistNewBioSequence(GenomePersister.java:887) ~[gemma-core-1.30.2.jar:?]
        at ubic.gemma.persistence.persister.GenomePersister.persistBioSequence(GenomePersister.java:309) ~[gemma-core-1.30.2.jar:?]
        at ubic.gemma.persistence.persister.GenomePersister.doPersist(GenomePersister.java:75) ~[gemma-core-1.30.2.jar:?]
        at ubic.gemma.persistence.persister.ArrayDesignPersister.doPersist(ArrayDesignPersister.java:53) ~[gemma-core-1.30.2.jar:?]
        at ubic.gemma.persistence.persister.ExpressionPersister.doPersist(ExpressionPersister.java:156) ~[gemma-core-1.30.2.jar:?]
        at ubic.gemma.persistence.persister.RelationshipPersister.doPersist(RelationshipPersister.java:59) ~[gemma-core-1.30.2.jar:?]
        at ubic.gemma.persistence.persister.PersisterHelperImpl.doPersist(PersisterHelperImpl.java:44) ~[gemma-core-1.30.2.jar:?]
        at ubic.gemma.persistence.persister.AbstractPersister.persist(AbstractPersister.java:101) ~[gemma-core-1.30.2.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:69) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:255) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:148) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:90) ~[spring-retry-1.0.3.RELEASE.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64) ~[spring-security-core-3.2.10.RELEASE.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.sun.proxy.$Proxy119.persist(Unknown Source) ~[?:?]
        at ubic.gemma.core.apps.GenericGenelistDesignGenerator.doWork(GenericGenelistDesignGenerator.java:254) ~[gemma-cli-1.30.2.jar:?]
        at ubic.gemma.core.util.AbstractCLI.executeCommand(AbstractCLI.java:133) [gemma-cli-1.30.2.jar:?]
        at ubic.gemma.core.apps.GemmaCLI.main(GemmaCLI.java:197) [gemma-cli-1.30.2.jar:?]
Caused by: org.hibernate.PersistentObjectException: detached entity passed to persist: ubic.gemma.model.common.description.DatabaseEntry
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:141) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
```

**Comment by arteymix** [comment]
@ppavlidis I'm currently running `genericPlatform  -t mouse`, but you can run other species with the patch.
