### ISSUE TITLE
Error while removing DEA

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#905]
Looks like an attempt to remove an already removed DEA. This happens in a retry attempt, so it's possible the initial remove kind of worked?

https://pavlidis-lab.slack.com/archives/C02LZHP6RB3/p1697231854829899

**Comment by ppavlidis** [comment]
Still relevant?

The error:

```
[Gemma - pool-280-thread-18 (2023-10-13 14:17:34,225)] ERROR ubic.gemma.persistence.retry.RetryLogger.close(50) | Retry failed after 2 attempts.

NullPointerException: No ubic.gemma.model.analysis.expression.diff.DifferentialExpressionAnalysis with ID 336360.
java.lang.NullPointerException: No ubic.gemma.model.analysis.expression.diff.DifferentialExpressionAnalysis with ID 336360.
    at java.util.Objects.requireNonNull(Objects.java:228)
    at ubic.gemma.persistence.service.AbstractService.ensureInSession(AbstractService.java:181)
    at ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionAnalysisServiceImpl.remove(DifferentialExpressionAnalysisServiceImpl.java:223)
    at ubic.gemma.persistence.service.analysis.expression.diff.DifferentialExpressionAnalysisServiceImpl.remove(DifferentialExpressionAnalysisServiceImpl.java:50)
```

**Comment by arteymix** [comment]
I haven't seen this in forever. I guess it can be considered resolved.
