### ISSUE TITLE
DEA results creation failure with continuous factor

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#943]
This was observed when using :

`gemma-cli diffExAnalyze -e GSE45642.1 -factors 40800,40803,40804 -subset 40802`

The actual cause might be upstream - the analysis that was completed is not showing up correctly, but the error is in the archive file creation stage.

```
ERROR 15131 [main] u.g.c.u.AbstractCLI.addErrorObject(360) | Error while processing ExpressionExperiment Id=24167 Name=Split part 1 of: Circadian patterns of gene expression in the human 
brain and disruption in major depressive disorder [collection of material = Experiment 1 ] Short Name=GSE45642.1:
        java.util.NoSuchElementException
java.util.NoSuchElementException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1471) ~[?:1.8.0_382]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1493) ~[?:1.8.0_382]
        at org.hibernate.collection.internal.AbstractPersistentCollection$IteratorProxy.next(AbstractPersistentCollection.java:810) ~[hibernate-core-4.2.21.Final.jar:4.2.21.Final]
        at ubic.gemma.core.analysis.service.ExpressionDataFileServiceImpl.analysisResultSetWithContrastsToString(ExpressionDataFileServiceImpl.java:622) ~[gemma-core-1.30.4.jar:?]
        at ubic.gemma.core.analysis.service.ExpressionDataFileServiceImpl.convertDiffExpressionResultSetData(ExpressionDataFileServiceImpl.java:763) ~[gemma-core-1.30.4.jar:?]
        at 
```

**Comment by ppavlidis** [comment]
Correction, the analysis is showing up correctly in the UI, must have been a temporary glitch. 

The file download is missing the resultset details file for the continuous factors.

**Comment by ppavlidis** [comment]
I can no longer reproduce this error but fixed a few other things that I noticed in the file generation when testing on this dataset. 
Also, some warnings we get during batch confound testing that were due to a missing check for factors that have only one factorvalue, which happens when we subset on that factor

In b0ee05384e0cc9229099502792bd254d11d845f8 and 4b3d63cc9752dc57d1f8bcbe1021196d593a8444
