### ISSUE TITLE
SSL error when retrieving CHEBI ontology

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#956]
```
SSLException: Connection reset
javax.net.ssl.SSLException: Connection reset
    at sun.security.ssl.Alert.createSSLException(Alert.java:127)
    at sun.security.ssl.TransportContext.fatal(TransportContext.java:331)
    at sun.security.ssl.TransportContext.fatal(TransportContext.java:274)
    at sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
```

**Comment by arteymix** [comment]
I'm not seeing this issue anymore, so I assume that they fixed their ssl certificate.
