### ISSUE TITLE
Batch correction suitability should be detected more thoroughly

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#959]
I ran into this problem with https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=27359

The experiment is badged as "no confound" and "no batch effect", but this is not really right.

The data cannot be batch corrected, presumably because the experimental design has only one sample per group, but this is not caught by the confound detector. Instead, it fails during the correction process (below).

It is wasteful to get to this point and then fail, instead we should detect more such cases and make sure the badges follow suit. 

```
2023-11-28 15:12:04,297 ERROR 11750 [main] u.g.c.u.AbstractCLI.executeCommand(162) | rnaseqDataAdd failed: ArrayIndexOutOfBoundsException: 35
java.lang.ArrayIndexOutOfBoundsException: 35
        at cern.colt.matrix.impl.DenseDoubleMatrix2D.getQuick(Unknown Source) ~[colt-1.2.0.jar:?]
        at ubic.basecode.math.linalg.QRDecomposition.<init>(QRDecomposition.java:212) ~[baseCode-1.1.19.jar:?]
        at ubic.basecode.math.linalg.QRDecomposition.<init>(QRDecomposition.java:99) ~[baseCode-1.1.19.jar:?]
        at ubic.basecode.math.linearmodels.LeastSquaresFit.lsf(LeastSquaresFit.java:1301) ~[baseCode-1.1.19.jar:?]
        at ubic.basecode.math.linearmodels.LeastSquaresFit.fit(LeastSquaresFit.java:1231) ~[baseCode-1.1.19.jar:?]
        at ubic.basecode.math.linearmodels.LeastSquaresFit.<init>(LeastSquaresFit.java:317) ~[baseCode-1.1.19.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ComBat.standardize(ComBat.java:285) ~[gemma-core-1.30.6.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ComBat.run(ComBat.java:212) ~[gemma-core-1.30.6.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ExpressionExperimentBatchCorrectionServiceImpl.doComBat(ExpressionExperimentBatchCorrectionServiceImpl.java:240) ~[gemma-core-1.30.6.jar:?]
        at ubic.gemma.core.analysis.preprocess.batcheffects.ExpressionExperimentBatchCorrectionServiceImpl.comBat(ExpressionExperimentBatchCorrectionServiceImpl.java:149) ~[gemma-core-1.30.6.jar:?]
```

**Comment by ppavlidis** [comment]
Gemma 2 disposition: Won't fix
