### ISSUE TITLE
collection error while running addGEOData --update

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/Gemma#986]
I don't think this is too serious but on occasion I am getting this reproducible error. On dev branch (1.32.0-SNAPSHOT 92cbd779220949247d65b379d73c2894cfa36d71)

Should reproduce with `gemma-cli addGEOData --update -e GSE11674`; also seen with GSE11794

```
2024-01-03 12:35:02,784 INFO 12459 [main] u.g.c.l.e.g.s.GeoServiceImpl.updateFromGEO(374) | GSE11674 Updated from GEO; 160 characteristics added/replaced
2024-01-03 12:35:02,864 ERROR 12459 [main] u.g.c.u.AbstractCLI.addErrorObject(451) | Error while processing GSE11674
org.springframework.dao.InvalidDataAccessApiUsageException: deleted object would be re-saved by cascade (remove deleted object from associations): [ubic.gemma.model.common.description.Characteristic#34666083]; nested exception is org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [ubic.gemma.model.common.description.Characteristic#34666083]
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:169) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.orm.hibernate4.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:682) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:564) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:270) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:166) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at com.sun.proxy.$Proxy183.updateFromGEO(Unknown Source) ~[?:?]
	at ubic.gemma.core.apps.LoadExpressionDataCli.processAccession(LoadExpressionDataCli.java:231) [classes/:?]
	at ubic.gemma.core.apps.LoadExpressionDataCli.doWork(LoadExpressionDataCli.java:178) [classes/:?]
	at ubic.gemma.core.util.AbstractCLI.executeCommand(AbstractCLI.java:203) [classes/:?]
	at ubic.gemma.core.apps.GemmaCLI.main(GemmaCLI.java:197) [classes/:?]
```

**Comment by arteymix** [comment]
I think this is caused by the logic of replacing characteristics with new, freshly retrieved from GEO.

**Comment by arteymix** [comment]
I've also fixed GSE11794.
